# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\ABLTrawlEvent.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ABLTrawlEvent(object):
    def setupUi(self, ABLTrawlEvent):
        ABLTrawlEvent.setObjectName(_fromUtf8("ABLTrawlEvent"))
        ABLTrawlEvent.resize(1019, 758)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ABLTrawlEvent.sizePolicy().hasHeightForWidth())
        ABLTrawlEvent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        ABLTrawlEvent.setFont(font)
        self.sciLabel = QtGui.QLabel(ABLTrawlEvent)
        self.sciLabel.setGeometry(QtCore.QRect(810, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.sciLabel.setFont(font)
        self.sciLabel.setAutoFillBackground(True)
        self.sciLabel.setFrameShape(QtGui.QFrame.Panel)
        self.sciLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.sciLabel.setLineWidth(1)
        self.sciLabel.setText(_fromUtf8(""))
        self.sciLabel.setObjectName(_fromUtf8("sciLabel"))
        self.label_14 = QtGui.QLabel(ABLTrawlEvent)
        self.label_14.setGeometry(QtCore.QRect(870, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox_2 = QtGui.QGroupBox(ABLTrawlEvent)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 670, 991, 81))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.commentBtn = QtGui.QPushButton(self.groupBox_2)
        self.commentBtn.setGeometry(QtCore.QRect(750, 10, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.commentBtn.setFont(font)
        self.commentBtn.setObjectName(_fromUtf8("commentBtn"))
        self.doneBtn = QtGui.QPushButton(self.groupBox_2)
        self.doneBtn.setGeometry(QtCore.QRect(870, 10, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.perfBox = QtGui.QComboBox(self.groupBox_2)
        self.perfBox.setEnabled(False)
        self.perfBox.setGeometry(QtCore.QRect(90, 33, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.perfBox.setFont(font)
        self.perfBox.setObjectName(_fromUtf8("perfBox"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(90, 8, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.elapseLabel = QtGui.QLabel(self.groupBox_2)
        self.elapseLabel.setEnabled(True)
        self.elapseLabel.setGeometry(QtCore.QRect(10, 33, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.elapseLabel.setFont(font)
        self.elapseLabel.setFrameShape(QtGui.QFrame.Box)
        self.elapseLabel.setText(_fromUtf8(""))
        self.elapseLabel.setObjectName(_fromUtf8("elapseLabel"))
        self.label_42 = QtGui.QLabel(self.groupBox_2)
        self.label_42.setGeometry(QtCore.QRect(24, 8, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.netDimBtn = QtGui.QPushButton(self.groupBox_2)
        self.netDimBtn.setGeometry(QtCore.QRect(630, 10, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.netDimBtn.setFont(font)
        self.netDimBtn.setObjectName(_fromUtf8("netDimBtn"))
        self.perfCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.perfCheckBox.setGeometry(QtCore.QRect(510, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.perfCheckBox.setFont(font)
        self.perfCheckBox.setObjectName(_fromUtf8("perfCheckBox"))
        self.label_5 = QtGui.QLabel(ABLTrawlEvent)
        self.label_5.setGeometry(QtCore.QRect(29, 9, 71, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.haulLabel = QtGui.QLabel(ABLTrawlEvent)
        self.haulLabel.setGeometry(QtCore.QRect(10, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.haulLabel.setFont(font)
        self.haulLabel.setFrameShape(QtGui.QFrame.Box)
        self.haulLabel.setText(_fromUtf8(""))
        self.haulLabel.setObjectName(_fromUtf8("haulLabel"))
        self.dataTable = QtGui.QTableWidget(ABLTrawlEvent)
        self.dataTable.setGeometry(QtCore.QRect(200, 190, 801, 471))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dataTable.setFont(font)
        self.dataTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dataTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.dataTable.setObjectName(_fromUtf8("dataTable"))
        self.dataTable.setColumnCount(4)
        self.dataTable.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        self.label_8 = QtGui.QLabel(ABLTrawlEvent)
        self.label_8.setGeometry(QtCore.QRect(450, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gearBox = QtGui.QComboBox(ABLTrawlEvent)
        self.gearBox.setGeometry(QtCore.QRect(410, 40, 181, 41))
        self.gearBox.setObjectName(_fromUtf8("gearBox"))
        self.buttonsGroup = QtGui.QGroupBox(ABLTrawlEvent)
        self.buttonsGroup.setEnabled(False)
        self.buttonsGroup.setGeometry(QtCore.QRect(4, 210, 191, 451))
        self.buttonsGroup.setTitle(_fromUtf8(""))
        self.buttonsGroup.setObjectName(_fromUtf8("buttonsGroup"))
        self.verticalLayoutWidget = QtGui.QWidget(self.buttonsGroup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 441))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 10, -1)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btn1 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn1.setMinimumSize(QtCore.QSize(170, 37))
        self.btn1.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn1.setFont(font)
        self.btn1.setText(_fromUtf8(""))
        self.btn1.setObjectName(_fromUtf8("btn1"))
        self.verticalLayout_3.addWidget(self.btn1)
        self.btn2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn2.setMinimumSize(QtCore.QSize(170, 37))
        self.btn2.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn2.setFont(font)
        self.btn2.setText(_fromUtf8(""))
        self.btn2.setObjectName(_fromUtf8("btn2"))
        self.verticalLayout_3.addWidget(self.btn2)
        self.btn3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn3.setMinimumSize(QtCore.QSize(170, 37))
        self.btn3.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn3.setFont(font)
        self.btn3.setText(_fromUtf8(""))
        self.btn3.setObjectName(_fromUtf8("btn3"))
        self.verticalLayout_3.addWidget(self.btn3)
        self.btn4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn4.setMinimumSize(QtCore.QSize(170, 37))
        self.btn4.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn4.setFont(font)
        self.btn4.setText(_fromUtf8(""))
        self.btn4.setObjectName(_fromUtf8("btn4"))
        self.verticalLayout_3.addWidget(self.btn4)
        self.btn5 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn5.setMinimumSize(QtCore.QSize(170, 37))
        self.btn5.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn5.setFont(font)
        self.btn5.setText(_fromUtf8(""))
        self.btn5.setObjectName(_fromUtf8("btn5"))
        self.verticalLayout_3.addWidget(self.btn5)
        self.btn6 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn6.setMinimumSize(QtCore.QSize(170, 37))
        self.btn6.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn6.setFont(font)
        self.btn6.setText(_fromUtf8(""))
        self.btn6.setObjectName(_fromUtf8("btn6"))
        self.verticalLayout_3.addWidget(self.btn6)
        self.btn7 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn7.setMinimumSize(QtCore.QSize(170, 37))
        self.btn7.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn7.setFont(font)
        self.btn7.setText(_fromUtf8(""))
        self.btn7.setObjectName(_fromUtf8("btn7"))
        self.verticalLayout_3.addWidget(self.btn7)
        self.btn8 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn8.setMinimumSize(QtCore.QSize(170, 37))
        self.btn8.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn8.setFont(font)
        self.btn8.setText(_fromUtf8(""))
        self.btn8.setObjectName(_fromUtf8("btn8"))
        self.verticalLayout_3.addWidget(self.btn8)
        self.btn9 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn9.setMinimumSize(QtCore.QSize(170, 37))
        self.btn9.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn9.setFont(font)
        self.btn9.setText(_fromUtf8(""))
        self.btn9.setObjectName(_fromUtf8("btn9"))
        self.verticalLayout_3.addWidget(self.btn9)
        self.btn10 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn10.setMinimumSize(QtCore.QSize(170, 37))
        self.btn10.setMaximumSize(QtCore.QSize(170, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn10.setFont(font)
        self.btn10.setText(_fromUtf8(""))
        self.btn10.setObjectName(_fromUtf8("btn10"))
        self.verticalLayout_3.addWidget(self.btn10)
        self.label = QtGui.QLabel(ABLTrawlEvent)
        self.label.setGeometry(QtCore.QRect(80, 186, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_27 = QtGui.QLabel(ABLTrawlEvent)
        self.label_27.setGeometry(QtCore.QRect(120, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.optionsGroup = QtGui.QGroupBox(ABLTrawlEvent)
        self.optionsGroup.setEnabled(False)
        self.optionsGroup.setGeometry(QtCore.QRect(10, 90, 991, 91))
        self.optionsGroup.setTitle(_fromUtf8(""))
        self.optionsGroup.setObjectName(_fromUtf8("optionsGroup"))
        self.gridLayoutWidget = QtGui.QWidget(self.optionsGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(330, 10, 501, 71))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.accessLabel1 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.accessLabel1.setFont(font)
        self.accessLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.accessLabel1.setObjectName(_fromUtf8("accessLabel1"))
        self.gridLayout.addWidget(self.accessLabel1, 0, 0, 1, 1)
        self.accessLabel2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.accessLabel2.setFont(font)
        self.accessLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.accessLabel2.setObjectName(_fromUtf8("accessLabel2"))
        self.gridLayout.addWidget(self.accessLabel2, 0, 1, 1, 1)
        self.accessBox1 = QtGui.QComboBox(self.gridLayoutWidget)
        self.accessBox1.setEnabled(False)
        self.accessBox1.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accessBox1.setFont(font)
        self.accessBox1.setObjectName(_fromUtf8("accessBox1"))
        self.gridLayout.addWidget(self.accessBox1, 1, 0, 1, 1)
        self.accessBox2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.accessBox2.setEnabled(False)
        self.accessBox2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accessBox2.setFont(font)
        self.accessBox2.setObjectName(_fromUtf8("accessBox2"))
        self.gridLayout.addWidget(self.accessBox2, 1, 1, 1, 1)
        self.accessBox3 = QtGui.QComboBox(self.gridLayoutWidget)
        self.accessBox3.setEnabled(False)
        self.accessBox3.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accessBox3.setFont(font)
        self.accessBox3.setObjectName(_fromUtf8("accessBox3"))
        self.gridLayout.addWidget(self.accessBox3, 1, 2, 1, 1)
        self.accessBox4 = QtGui.QComboBox(self.gridLayoutWidget)
        self.accessBox4.setEnabled(False)
        self.accessBox4.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accessBox4.setFont(font)
        self.accessBox4.setObjectName(_fromUtf8("accessBox4"))
        self.gridLayout.addWidget(self.accessBox4, 1, 3, 1, 1)
        self.accessLabel3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.accessLabel3.setFont(font)
        self.accessLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.accessLabel3.setObjectName(_fromUtf8("accessLabel3"))
        self.gridLayout.addWidget(self.accessLabel3, 0, 2, 1, 1)
        self.accessLabel4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.accessLabel4.setFont(font)
        self.accessLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.accessLabel4.setObjectName(_fromUtf8("accessLabel4"))
        self.gridLayout.addWidget(self.accessLabel4, 0, 3, 1, 1)
        self.typeBox = QtGui.QComboBox(self.optionsGroup)
        self.typeBox.setEnabled(False)
        self.typeBox.setGeometry(QtCore.QRect(10, 50, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.typeBox.setFont(font)
        self.typeBox.setObjectName(_fromUtf8("typeBox"))
        self.label_4 = QtGui.QLabel(self.optionsGroup)
        self.label_4.setGeometry(QtCore.QRect(14, 15, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.marMammalBox = QtGui.QCheckBox(self.optionsGroup)
        self.marMammalBox.setGeometry(QtCore.QRect(840, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.marMammalBox.setFont(font)
        self.marMammalBox.setObjectName(_fromUtf8("marMammalBox"))
        self.seaBirdBox = QtGui.QCheckBox(self.optionsGroup)
        self.seaBirdBox.setGeometry(QtCore.QRect(840, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seaBirdBox.setFont(font)
        self.seaBirdBox.setObjectName(_fromUtf8("seaBirdBox"))
        self.label_28 = QtGui.QLabel(ABLTrawlEvent)
        self.label_28.setGeometry(QtCore.QRect(710, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.frame = QtGui.QFrame(ABLTrawlEvent)
        self.frame.setGeometry(QtCore.QRect(710, 40, 81, 41))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.depthEndBtn = QtGui.QPushButton(self.frame)
        self.depthEndBtn.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.depthEndBtn.setText(_fromUtf8(""))
        self.depthEndBtn.setObjectName(_fromUtf8("depthEndBtn"))
        self.label_29 = QtGui.QLabel(ABLTrawlEvent)
        self.label_29.setGeometry(QtCore.QRect(310, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(ABLTrawlEvent)
        self.label_30.setGeometry(QtCore.QRect(210, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(ABLTrawlEvent)
        self.label_31.setGeometry(QtCore.QRect(600, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.frame_2 = QtGui.QFrame(ABLTrawlEvent)
        self.frame_2.setGeometry(QtCore.QRect(610, 40, 81, 41))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.depthStartBtn = QtGui.QPushButton(self.frame_2)
        self.depthStartBtn.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.depthStartBtn.setText(_fromUtf8(""))
        self.depthStartBtn.setObjectName(_fromUtf8("depthStartBtn"))
        self.frame_3 = QtGui.QFrame(ABLTrawlEvent)
        self.frame_3.setGeometry(QtCore.QRect(310, 40, 81, 41))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.stratumBtn = QtGui.QPushButton(self.frame_3)
        self.stratumBtn.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.stratumBtn.setText(_fromUtf8(""))
        self.stratumBtn.setObjectName(_fromUtf8("stratumBtn"))
        self.frame_4 = QtGui.QFrame(ABLTrawlEvent)
        self.frame_4.setGeometry(QtCore.QRect(210, 40, 81, 41))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.transBtn = QtGui.QPushButton(self.frame_4)
        self.transBtn.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.transBtn.setText(_fromUtf8(""))
        self.transBtn.setObjectName(_fromUtf8("transBtn"))
        self.frame_5 = QtGui.QFrame(ABLTrawlEvent)
        self.frame_5.setGeometry(QtCore.QRect(110, 40, 81, 41))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.stnBtn = QtGui.QPushButton(self.frame_5)
        self.stnBtn.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.stnBtn.setText(_fromUtf8(""))
        self.stnBtn.setObjectName(_fromUtf8("stnBtn"))

        self.retranslateUi(ABLTrawlEvent)
        QtCore.QMetaObject.connectSlotsByName(ABLTrawlEvent)

    def retranslateUi(self, ABLTrawlEvent):
        ABLTrawlEvent.setWindowTitle(_translate("ABLTrawlEvent", "CLAMS Haul", None))
        self.label_14.setText(_translate("ABLTrawlEvent", "Scientist", None))
        self.commentBtn.setText(_translate("ABLTrawlEvent", "Comment", None))
        self.doneBtn.setText(_translate("ABLTrawlEvent", "Done", None))
        self.label_6.setText(_translate("ABLTrawlEvent", " Gear Performance", None))
        self.label_42.setText(_translate("ABLTrawlEvent", "Time", None))
        self.netDimBtn.setText(_translate("ABLTrawlEvent", "Net\n"
"Dimensions", None))
        self.perfCheckBox.setText(_translate("ABLTrawlEvent", "Show All", None))
        self.label_5.setText(_translate("ABLTrawlEvent", "Event", None))
        item = self.dataTable.verticalHeaderItem(0)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(1)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(2)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(3)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(4)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(5)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(6)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(7)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(8)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.verticalHeaderItem(9)
        item.setText(_translate("ABLTrawlEvent", "New Row", None))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("ABLTrawlEvent", "Time", None))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("ABLTrawlEvent", "Latitude", None))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("ABLTrawlEvent", "Longitude", None))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("ABLTrawlEvent", "Bottom Depth", None))
        self.label_8.setText(_translate("ABLTrawlEvent", "Trawl Gear", None))
        self.label.setText(_translate("ABLTrawlEvent", "Actions", None))
        self.label_27.setText(_translate("ABLTrawlEvent", "Station", None))
        self.accessLabel1.setText(_translate("ABLTrawlEvent", "1", None))
        self.accessLabel2.setText(_translate("ABLTrawlEvent", "2", None))
        self.accessLabel3.setText(_translate("ABLTrawlEvent", "3", None))
        self.accessLabel4.setText(_translate("ABLTrawlEvent", "4", None))
        self.label_4.setText(_translate("ABLTrawlEvent", "Haul Type", None))
        self.marMammalBox.setText(_translate("ABLTrawlEvent", "Marine Mammals\n"
" seen?", None))
        self.seaBirdBox.setText(_translate("ABLTrawlEvent", "Endangered\n"
"Seabirds seen?", None))
        self.label_28.setText(_translate("ABLTrawlEvent", "Depth End", None))
        self.label_29.setText(_translate("ABLTrawlEvent", "Stratum", None))
        self.label_30.setText(_translate("ABLTrawlEvent", "Transect", None))
        self.label_31.setText(_translate("ABLTrawlEvent", "Depth Start", None))

