# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\AddCatchSpcDlg_alt2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_addcatchspcDlg(object):
    def setupUi(self, addcatchspcDlg):
        addcatchspcDlg.setObjectName(_fromUtf8("addcatchspcDlg"))
        addcatchspcDlg.setWindowModality(QtCore.Qt.NonModal)
        addcatchspcDlg.resize(780, 676)
        self.frame = QtGui.QFrame(addcatchspcDlg)
        self.frame.setGeometry(QtCore.QRect(10, 620, 761, 51))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.addBtn = QtGui.QPushButton(self.frame)
        self.addBtn.setMinimumSize(QtCore.QSize(141, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName(_fromUtf8("addBtn"))
        self.horizontalLayout.addWidget(self.addBtn)
        self.mixBtn = QtGui.QPushButton(self.frame)
        self.mixBtn.setMinimumSize(QtCore.QSize(141, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mixBtn.setFont(font)
        self.mixBtn.setObjectName(_fromUtf8("mixBtn"))
        self.horizontalLayout.addWidget(self.mixBtn)
        self.addmixBtn = QtGui.QPushButton(self.frame)
        self.addmixBtn.setMinimumSize(QtCore.QSize(141, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addmixBtn.setFont(font)
        self.addmixBtn.setObjectName(_fromUtf8("addmixBtn"))
        self.horizontalLayout.addWidget(self.addmixBtn)
        self.wholeBtn = QtGui.QPushButton(self.frame)
        self.wholeBtn.setMinimumSize(QtCore.QSize(141, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wholeBtn.setFont(font)
        self.wholeBtn.setObjectName(_fromUtf8("wholeBtn"))
        self.horizontalLayout.addWidget(self.wholeBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.doneBtn = QtGui.QPushButton(self.frame)
        self.doneBtn.setMinimumSize(QtCore.QSize(141, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.horizontalLayout.addWidget(self.doneBtn)
        self.groupBox = QtGui.QGroupBox(addcatchspcDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 450, 761, 171))
        self.groupBox.setMinimumSize(QtCore.QSize(621, 0))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.E_Btn = QtGui.QPushButton(self.groupBox)
        self.E_Btn.setGeometry(QtCore.QRect(130, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.E_Btn.setFont(font)
        self.E_Btn.setObjectName(_fromUtf8("E_Btn"))
        self.I_Btn = QtGui.QPushButton(self.groupBox)
        self.I_Btn.setGeometry(QtCore.QRect(430, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.I_Btn.setFont(font)
        self.I_Btn.setObjectName(_fromUtf8("I_Btn"))
        self.O_Btn = QtGui.QPushButton(self.groupBox)
        self.O_Btn.setGeometry(QtCore.QRect(490, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.O_Btn.setFont(font)
        self.O_Btn.setObjectName(_fromUtf8("O_Btn"))
        self.U_Btn = QtGui.QPushButton(self.groupBox)
        self.U_Btn.setGeometry(QtCore.QRect(370, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.U_Btn.setFont(font)
        self.U_Btn.setObjectName(_fromUtf8("U_Btn"))
        self.N_Btn = QtGui.QPushButton(self.groupBox)
        self.N_Btn.setGeometry(QtCore.QRect(360, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.N_Btn.setFont(font)
        self.N_Btn.setObjectName(_fromUtf8("N_Btn"))
        self.D_Btn = QtGui.QPushButton(self.groupBox)
        self.D_Btn.setGeometry(QtCore.QRect(150, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.D_Btn.setFont(font)
        self.D_Btn.setObjectName(_fromUtf8("D_Btn"))
        self.G_Btn = QtGui.QPushButton(self.groupBox)
        self.G_Btn.setGeometry(QtCore.QRect(270, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.G_Btn.setFont(font)
        self.G_Btn.setObjectName(_fromUtf8("G_Btn"))
        self.K_Btn = QtGui.QPushButton(self.groupBox)
        self.K_Btn.setGeometry(QtCore.QRect(450, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.K_Btn.setFont(font)
        self.K_Btn.setObjectName(_fromUtf8("K_Btn"))
        self.R_Btn = QtGui.QPushButton(self.groupBox)
        self.R_Btn.setGeometry(QtCore.QRect(190, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.R_Btn.setFont(font)
        self.R_Btn.setObjectName(_fromUtf8("R_Btn"))
        self.F_Btn = QtGui.QPushButton(self.groupBox)
        self.F_Btn.setGeometry(QtCore.QRect(210, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.F_Btn.setFont(font)
        self.F_Btn.setObjectName(_fromUtf8("F_Btn"))
        self.P_Btn = QtGui.QPushButton(self.groupBox)
        self.P_Btn.setGeometry(QtCore.QRect(550, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P_Btn.setFont(font)
        self.P_Btn.setObjectName(_fromUtf8("P_Btn"))
        self.Q_Btn = QtGui.QPushButton(self.groupBox)
        self.Q_Btn.setGeometry(QtCore.QRect(10, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Q_Btn.setFont(font)
        self.Q_Btn.setObjectName(_fromUtf8("Q_Btn"))
        self.T_Btn = QtGui.QPushButton(self.groupBox)
        self.T_Btn.setGeometry(QtCore.QRect(250, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.T_Btn.setFont(font)
        self.T_Btn.setObjectName(_fromUtf8("T_Btn"))
        self.L_Btn = QtGui.QPushButton(self.groupBox)
        self.L_Btn.setGeometry(QtCore.QRect(510, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.L_Btn.setFont(font)
        self.L_Btn.setObjectName(_fromUtf8("L_Btn"))
        self.W_Btn = QtGui.QPushButton(self.groupBox)
        self.W_Btn.setGeometry(QtCore.QRect(70, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.W_Btn.setFont(font)
        self.W_Btn.setObjectName(_fromUtf8("W_Btn"))
        self.V_Btn = QtGui.QPushButton(self.groupBox)
        self.V_Btn.setGeometry(QtCore.QRect(240, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.V_Btn.setFont(font)
        self.V_Btn.setObjectName(_fromUtf8("V_Btn"))
        self.S_Btn = QtGui.QPushButton(self.groupBox)
        self.S_Btn.setGeometry(QtCore.QRect(90, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.S_Btn.setFont(font)
        self.S_Btn.setObjectName(_fromUtf8("S_Btn"))
        self.M_Btn = QtGui.QPushButton(self.groupBox)
        self.M_Btn.setGeometry(QtCore.QRect(420, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.M_Btn.setFont(font)
        self.M_Btn.setObjectName(_fromUtf8("M_Btn"))
        self.Y_Btn = QtGui.QPushButton(self.groupBox)
        self.Y_Btn.setGeometry(QtCore.QRect(310, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Y_Btn.setFont(font)
        self.Y_Btn.setObjectName(_fromUtf8("Y_Btn"))
        self.X_Btn = QtGui.QPushButton(self.groupBox)
        self.X_Btn.setGeometry(QtCore.QRect(120, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.X_Btn.setFont(font)
        self.X_Btn.setObjectName(_fromUtf8("X_Btn"))
        self.A_Btn = QtGui.QPushButton(self.groupBox)
        self.A_Btn.setGeometry(QtCore.QRect(30, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.A_Btn.setFont(font)
        self.A_Btn.setObjectName(_fromUtf8("A_Btn"))
        self.H_Btn = QtGui.QPushButton(self.groupBox)
        self.H_Btn.setGeometry(QtCore.QRect(330, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.H_Btn.setFont(font)
        self.H_Btn.setObjectName(_fromUtf8("H_Btn"))
        self.J_Btn = QtGui.QPushButton(self.groupBox)
        self.J_Btn.setGeometry(QtCore.QRect(390, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.J_Btn.setFont(font)
        self.J_Btn.setObjectName(_fromUtf8("J_Btn"))
        self.Z_Btn = QtGui.QPushButton(self.groupBox)
        self.Z_Btn.setGeometry(QtCore.QRect(60, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Z_Btn.setFont(font)
        self.Z_Btn.setObjectName(_fromUtf8("Z_Btn"))
        self.C_Btn = QtGui.QPushButton(self.groupBox)
        self.C_Btn.setGeometry(QtCore.QRect(180, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.C_Btn.setFont(font)
        self.C_Btn.setObjectName(_fromUtf8("C_Btn"))
        self.B_Btn = QtGui.QPushButton(self.groupBox)
        self.B_Btn.setGeometry(QtCore.QRect(300, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.B_Btn.setFont(font)
        self.B_Btn.setObjectName(_fromUtf8("B_Btn"))
        self.backBtn = QtGui.QPushButton(self.groupBox)
        self.backBtn.setGeometry(QtCore.QRect(610, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName(_fromUtf8("backBtn"))
        self.clearBtn = QtGui.QPushButton(self.groupBox)
        self.clearBtn.setGeometry(QtCore.QRect(610, 60, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName(_fromUtf8("clearBtn"))
        self.nameTab = QtGui.QTabWidget(addcatchspcDlg)
        self.nameTab.setGeometry(QtCore.QRect(20, 10, 401, 381))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameTab.setFont(font)
        self.nameTab.setObjectName(_fromUtf8("nameTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.fullspcCList = QtGui.QListWidget(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fullspcCList.setFont(font)
        self.fullspcCList.setObjectName(_fromUtf8("fullspcCList"))
        self.horizontalLayout_4.addWidget(self.fullspcCList)
        self.nameTab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fullspcSList = QtGui.QListWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fullspcSList.setFont(font)
        self.fullspcSList.setObjectName(_fromUtf8("fullspcSList"))
        self.horizontalLayout_2.addWidget(self.fullspcSList)
        self.nameTab.addTab(self.tab_2, _fromUtf8(""))
        self.picLabel = QtGui.QLabel(addcatchspcDlg)
        self.picLabel.setGeometry(QtCore.QRect(436, 99, 331, 211))
        self.picLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.picLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.picLabel.setText(_fromUtf8(""))
        self.picLabel.setObjectName(_fromUtf8("picLabel"))
        self.groupBox_2 = QtGui.QGroupBox(addcatchspcDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 377, 321, 71))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radio10 = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radio10.setFont(font)
        self.radio10.setObjectName(_fromUtf8("radio10"))
        self.horizontalLayout_3.addWidget(self.radio10)
        self.radioFull = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioFull.setFont(font)
        self.radioFull.setChecked(True)
        self.radioFull.setAutoRepeat(False)
        self.radioFull.setObjectName(_fromUtf8("radioFull"))
        self.horizontalLayout_3.addWidget(self.radioFull)
        self.label = QtGui.QLabel(addcatchspcDlg)
        self.label.setGeometry(QtCore.QRect(526, 346, 121, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.spcLabel = QtGui.QLabel(addcatchspcDlg)
        self.spcLabel.setGeometry(QtCore.QRect(450, 30, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spcLabel.setFont(font)
        self.spcLabel.setText(_fromUtf8(""))
        self.spcLabel.setObjectName(_fromUtf8("spcLabel"))
        self.lineEdit = QtGui.QLineEdit(addcatchspcDlg)
        self.lineEdit.setGeometry(QtCore.QRect(20, 400, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))

        self.retranslateUi(addcatchspcDlg)
        self.nameTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(addcatchspcDlg)

    def retranslateUi(self, addcatchspcDlg):
        addcatchspcDlg.setWindowTitle(_translate("addcatchspcDlg", "Add Species", None))
        self.addBtn.setText(_translate("addcatchspcDlg", "Add to List", None))
        self.mixBtn.setText(_translate("addcatchspcDlg", "Create Mix", None))
        self.addmixBtn.setText(_translate("addcatchspcDlg", "Add to Mix", None))
        self.wholeBtn.setText(_translate("addcatchspcDlg", "Whole Haul", None))
        self.doneBtn.setText(_translate("addcatchspcDlg", "Done", None))
        self.E_Btn.setText(_translate("addcatchspcDlg", "E", None))
        self.I_Btn.setText(_translate("addcatchspcDlg", "I", None))
        self.O_Btn.setText(_translate("addcatchspcDlg", "O", None))
        self.U_Btn.setText(_translate("addcatchspcDlg", "U", None))
        self.N_Btn.setText(_translate("addcatchspcDlg", "N", None))
        self.D_Btn.setText(_translate("addcatchspcDlg", "D", None))
        self.G_Btn.setText(_translate("addcatchspcDlg", "G", None))
        self.K_Btn.setText(_translate("addcatchspcDlg", "K", None))
        self.R_Btn.setText(_translate("addcatchspcDlg", "R", None))
        self.F_Btn.setText(_translate("addcatchspcDlg", "F", None))
        self.P_Btn.setText(_translate("addcatchspcDlg", "P", None))
        self.Q_Btn.setText(_translate("addcatchspcDlg", "Q", None))
        self.T_Btn.setText(_translate("addcatchspcDlg", "T", None))
        self.L_Btn.setText(_translate("addcatchspcDlg", "L", None))
        self.W_Btn.setText(_translate("addcatchspcDlg", "W", None))
        self.V_Btn.setText(_translate("addcatchspcDlg", "V", None))
        self.S_Btn.setText(_translate("addcatchspcDlg", "S", None))
        self.M_Btn.setText(_translate("addcatchspcDlg", "M", None))
        self.Y_Btn.setText(_translate("addcatchspcDlg", "Y", None))
        self.X_Btn.setText(_translate("addcatchspcDlg", "X", None))
        self.A_Btn.setText(_translate("addcatchspcDlg", "A", None))
        self.H_Btn.setText(_translate("addcatchspcDlg", "H", None))
        self.J_Btn.setText(_translate("addcatchspcDlg", "J", None))
        self.Z_Btn.setText(_translate("addcatchspcDlg", "Z", None))
        self.C_Btn.setText(_translate("addcatchspcDlg", "C", None))
        self.B_Btn.setText(_translate("addcatchspcDlg", "B", None))
        self.backBtn.setText(_translate("addcatchspcDlg", "Backspace", None))
        self.clearBtn.setText(_translate("addcatchspcDlg", "Clear", None))
        self.nameTab.setTabText(self.nameTab.indexOf(self.tab), _translate("addcatchspcDlg", "Common", None))
        self.nameTab.setTabText(self.nameTab.indexOf(self.tab_2), _translate("addcatchspcDlg", "Scientific", None))
        self.radio10.setText(_translate("addcatchspcDlg", "Last 10 Hauls", None))
        self.radioFull.setText(_translate("addcatchspcDlg", "Full List", None))
        self.label.setText(_translate("addcatchspcDlg", "Search Domain", None))

