# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\CLAMSSpeciesFix.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_clamsSpeciesFix(object):
    def setupUi(self, clamsSpeciesFix):
        clamsSpeciesFix.setObjectName(_fromUtf8("clamsSpeciesFix"))
        clamsSpeciesFix.resize(1020, 645)
        self.bottomBox = QtGui.QGroupBox(clamsSpeciesFix)
        self.bottomBox.setGeometry(QtCore.QRect(20, 560, 981, 61))
        self.bottomBox.setTitle(_fromUtf8(""))
        self.bottomBox.setObjectName(_fromUtf8("bottomBox"))
        self.doneBtn = QtGui.QPushButton(self.bottomBox)
        self.doneBtn.setGeometry(QtCore.QRect(800, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.applyChangeBtn = QtGui.QPushButton(self.bottomBox)
        self.applyChangeBtn.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.applyChangeBtn.setFont(font)
        self.applyChangeBtn.setObjectName(_fromUtf8("applyChangeBtn"))
        self.clearBtn = QtGui.QPushButton(self.bottomBox)
        self.clearBtn.setGeometry(QtCore.QRect(251, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName(_fromUtf8("clearBtn"))
        self.label_3 = QtGui.QLabel(clamsSpeciesFix)
        self.label_3.setGeometry(QtCore.QRect(380, 10, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.measureView = QtGui.QTableView(clamsSpeciesFix)
        self.measureView.setGeometry(QtCore.QRect(380, 40, 621, 501))
        self.measureView.setObjectName(_fromUtf8("measureView"))
        self.measureView.verticalHeader().setVisible(False)
        self.frame = QtGui.QFrame(clamsSpeciesFix)
        self.frame.setGeometry(QtCore.QRect(20, 40, 351, 181))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.scientistBox = QtGui.QComboBox(self.frame)
        self.scientistBox.setGeometry(QtCore.QRect(130, 15, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scientistBox.setFont(font)
        self.scientistBox.setObjectName(_fromUtf8("scientistBox"))
        self.workstationBox = QtGui.QComboBox(self.frame)
        self.workstationBox.setGeometry(QtCore.QRect(130, 68, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.workstationBox.setFont(font)
        self.workstationBox.setObjectName(_fromUtf8("workstationBox"))
        self.speciesBox = QtGui.QComboBox(self.frame)
        self.speciesBox.setGeometry(QtCore.QRect(130, 121, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.speciesBox.setFont(font)
        self.speciesBox.setObjectName(_fromUtf8("speciesBox"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 78, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 25, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 131, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_4 = QtGui.QLabel(clamsSpeciesFix)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.frame_2 = QtGui.QFrame(clamsSpeciesFix)
        self.frame_2.setGeometry(QtCore.QRect(20, 259, 351, 281))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.startIDBtn = QtGui.QPushButton(self.frame_2)
        self.startIDBtn.setGeometry(QtCore.QRect(10, 16, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startIDBtn.setFont(font)
        self.startIDBtn.setObjectName(_fromUtf8("startIDBtn"))
        self.endIDBtn = QtGui.QPushButton(self.frame_2)
        self.endIDBtn.setGeometry(QtCore.QRect(10, 71, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.endIDBtn.setFont(font)
        self.endIDBtn.setObjectName(_fromUtf8("endIDBtn"))
        self.startIDLabel = QtGui.QLabel(self.frame_2)
        self.startIDLabel.setGeometry(QtCore.QRect(200, 16, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startIDLabel.setFont(font)
        self.startIDLabel.setFrameShape(QtGui.QFrame.Box)
        self.startIDLabel.setText(_fromUtf8(""))
        self.startIDLabel.setObjectName(_fromUtf8("startIDLabel"))
        self.endIDLabel = QtGui.QLabel(self.frame_2)
        self.endIDLabel.setGeometry(QtCore.QRect(200, 71, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endIDLabel.setFont(font)
        self.endIDLabel.setFrameShape(QtGui.QFrame.Box)
        self.endIDLabel.setText(_fromUtf8(""))
        self.endIDLabel.setObjectName(_fromUtf8("endIDLabel"))
        self.reassignTabs = QtGui.QTabWidget(self.frame_2)
        self.reassignTabs.setGeometry(QtCore.QRect(5, 130, 341, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reassignTabs.setFont(font)
        self.reassignTabs.setObjectName(_fromUtf8("reassignTabs"))
        self.species = QtGui.QWidget()
        self.species.setObjectName(_fromUtf8("species"))
        self.newSpeciesBox = QtGui.QComboBox(self.species)
        self.newSpeciesBox.setGeometry(QtCore.QRect(10, 38, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.newSpeciesBox.setFont(font)
        self.newSpeciesBox.setObjectName(_fromUtf8("newSpeciesBox"))
        self.label_9 = QtGui.QLabel(self.species)
        self.label_9.setGeometry(QtCore.QRect(11, 8, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.reassignTabs.addTab(self.species, _fromUtf8(""))
        self.sex = QtGui.QWidget()
        self.sex.setObjectName(_fromUtf8("sex"))
        self.label_10 = QtGui.QLabel(self.sex)
        self.label_10.setGeometry(QtCore.QRect(11, 8, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.newSexBox = QtGui.QComboBox(self.sex)
        self.newSexBox.setGeometry(QtCore.QRect(10, 38, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.newSexBox.setFont(font)
        self.newSexBox.setObjectName(_fromUtf8("newSexBox"))
        self.newSexBox.addItem(_fromUtf8(""))
        self.newSexBox.addItem(_fromUtf8(""))
        self.newSexBox.addItem(_fromUtf8(""))
        self.reassignTabs.addTab(self.sex, _fromUtf8(""))
        self.label_8 = QtGui.QLabel(clamsSpeciesFix)
        self.label_8.setGeometry(QtCore.QRect(20, 223, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))

        self.retranslateUi(clamsSpeciesFix)
        self.reassignTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(clamsSpeciesFix)

    def retranslateUi(self, clamsSpeciesFix):
        clamsSpeciesFix.setWindowTitle(_translate("clamsSpeciesFix", "CLAMS Fix Species", None))
        self.doneBtn.setText(_translate("clamsSpeciesFix", "Done", None))
        self.applyChangeBtn.setText(_translate("clamsSpeciesFix", "Apply Fix!", None))
        self.clearBtn.setText(_translate("clamsSpeciesFix", "Clear Filters", None))
        self.label_3.setText(_translate("clamsSpeciesFix", "Measurement values", None))
        self.label_5.setText(_translate("clamsSpeciesFix", "Workstation", None))
        self.label_6.setText(_translate("clamsSpeciesFix", "Scientist", None))
        self.label_7.setText(_translate("clamsSpeciesFix", "Species", None))
        self.label_4.setText(_translate("clamsSpeciesFix", "Filter by", None))
        self.startIDBtn.setText(_translate("clamsSpeciesFix", "Start specimen_ID", None))
        self.endIDBtn.setText(_translate("clamsSpeciesFix", "End specimen_ID", None))
        self.startIDLabel.setToolTip(_translate("clamsSpeciesFix", "<html><head/><body><p>The starting specimen ID the fix will be applied to.</p></body></html>", None))
        self.endIDLabel.setToolTip(_translate("clamsSpeciesFix", "<html><head/><body><p>The ending specimen ID the fix will be applied to.</p></body></html>", None))
        self.reassignTabs.setToolTip(_translate("clamsSpeciesFix", "<html><head/><body><p>Select the &quot;Species&quot; tab a choose a species to assign to the specimen ids defined above. Select the &quot;Sex&quot; tab to choose a sex to assign to the specimen defined above.</p></body></html>", None))
        self.label_9.setText(_translate("clamsSpeciesFix", "New Species Assignment", None))
        self.reassignTabs.setTabText(self.reassignTabs.indexOf(self.species), _translate("clamsSpeciesFix", "Reassign Species", None))
        self.label_10.setText(_translate("clamsSpeciesFix", "New Sex Assignment", None))
        self.newSexBox.setItemText(0, _translate("clamsSpeciesFix", "Male", None))
        self.newSexBox.setItemText(1, _translate("clamsSpeciesFix", "Female", None))
        self.newSexBox.setItemText(2, _translate("clamsSpeciesFix", "Unsexed", None))
        self.reassignTabs.setTabText(self.reassignTabs.indexOf(self.sex), _translate("clamsSpeciesFix", "Reassign Sex", None))
        self.label_8.setText(_translate("clamsSpeciesFix", "Reassign species or sex", None))

