# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CLAMS_archive\CLAMS\ui\xga\CLAMSLength.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_clamsLength(object):
    def setupUi(self, clamsLength):
        clamsLength.setObjectName(_fromUtf8("clamsLength"))
        clamsLength.resize(1020, 645)
        self.sciLabel = QtGui.QLabel(clamsLength)
        self.sciLabel.setGeometry(QtCore.QRect(610, 37, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sciLabel.setFont(font)
        self.sciLabel.setAutoFillBackground(True)
        self.sciLabel.setFrameShape(QtGui.QFrame.Panel)
        self.sciLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.sciLabel.setLineWidth(1)
        self.sciLabel.setText(_fromUtf8(""))
        self.sciLabel.setObjectName(_fromUtf8("sciLabel"))
        self.bottomBox = QtGui.QGroupBox(clamsLength)
        self.bottomBox.setGeometry(QtCore.QRect(20, 550, 981, 61))
        self.bottomBox.setTitle(_fromUtf8(""))
        self.bottomBox.setObjectName(_fromUtf8("bottomBox"))
        self.deleteBtn = QtGui.QPushButton(self.bottomBox)
        self.deleteBtn.setGeometry(QtCore.QRect(379, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName(_fromUtf8("deleteBtn"))
        self.doneBtn = QtGui.QPushButton(self.bottomBox)
        self.doneBtn.setGeometry(QtCore.QRect(800, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.extraBtn_2 = QtGui.QPushButton(self.bottomBox)
        self.extraBtn_2.setGeometry(QtCore.QRect(200, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.extraBtn_2.setFont(font)
        self.extraBtn_2.setCheckable(True)
        self.extraBtn_2.setObjectName(_fromUtf8("extraBtn_2"))
        self.commentBtn = QtGui.QPushButton(self.bottomBox)
        self.commentBtn.setGeometry(QtCore.QRect(560, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.commentBtn.setFont(font)
        self.commentBtn.setObjectName(_fromUtf8("commentBtn"))
        self.manualBtn = QtGui.QPushButton(self.bottomBox)
        self.manualBtn.setGeometry(QtCore.QRect(20, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.manualBtn.setFont(font)
        self.manualBtn.setObjectName(_fromUtf8("manualBtn"))
        self.sumTable = QtGui.QTableWidget(clamsLength)
        self.sumTable.setEnabled(False)
        self.sumTable.setGeometry(QtCore.QRect(488, 400, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sumTable.setFont(font)
        self.sumTable.setObjectName(_fromUtf8("sumTable"))
        self.sumTable.setColumnCount(0)
        self.sumTable.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.sumTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sumTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sumTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sumTable.setVerticalHeaderItem(3, item)
        self.label_3 = QtGui.QLabel(clamsLength)
        self.label_3.setGeometry(QtCore.QRect(689, 93, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(clamsLength)
        self.label_4.setGeometry(QtCore.QRect(488, 375, 119, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.otherBox = QtGui.QGroupBox(clamsLength)
        self.otherBox.setEnabled(False)
        self.otherBox.setGeometry(QtCore.QRect(488, 210, 171, 151))
        self.otherBox.setTitle(_fromUtf8(""))
        self.otherBox.setObjectName(_fromUtf8("otherBox"))
        self.label = QtGui.QLabel(self.otherBox)
        self.label.setGeometry(QtCore.QRect(10, 80, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.otherBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.samplingMethodBox = QtGui.QComboBox(self.otherBox)
        self.samplingMethodBox.setGeometry(QtCore.QRect(10, 31, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.samplingMethodBox.setFont(font)
        self.samplingMethodBox.setObjectName(_fromUtf8("samplingMethodBox"))
        self.lengthTypeBox = QtGui.QComboBox(self.otherBox)
        self.lengthTypeBox.setGeometry(QtCore.QRect(10, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lengthTypeBox.setFont(font)
        self.lengthTypeBox.setObjectName(_fromUtf8("lengthTypeBox"))
        self.label_5 = QtGui.QLabel(clamsLength)
        self.label_5.setGeometry(QtCore.QRect(21, 14, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.speciesList = QtGui.QListWidget(clamsLength)
        self.speciesList.setGeometry(QtCore.QRect(20, 40, 281, 341))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.speciesList.setFont(font)
        self.speciesList.setObjectName(_fromUtf8("speciesList"))
        self.groupSexBox = QtGui.QGroupBox(clamsLength)
        self.groupSexBox.setEnabled(False)
        self.groupSexBox.setGeometry(QtCore.QRect(320, 210, 141, 171))
        self.groupSexBox.setTitle(_fromUtf8(""))
        self.groupSexBox.setObjectName(_fromUtf8("groupSexBox"))
        self.maleBtn = QtGui.QPushButton(self.groupSexBox)
        self.maleBtn.setGeometry(QtCore.QRect(10, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maleBtn.setFont(font)
        self.maleBtn.setCheckable(True)
        self.maleBtn.setObjectName(_fromUtf8("maleBtn"))
        self.femaleBtn = QtGui.QPushButton(self.groupSexBox)
        self.femaleBtn.setGeometry(QtCore.QRect(10, 60, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.femaleBtn.setFont(font)
        self.femaleBtn.setCheckable(True)
        self.femaleBtn.setObjectName(_fromUtf8("femaleBtn"))
        self.unsexBtn = QtGui.QPushButton(self.groupSexBox)
        self.unsexBtn.setGeometry(QtCore.QRect(10, 110, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unsexBtn.setFont(font)
        self.unsexBtn.setCheckable(True)
        self.unsexBtn.setObjectName(_fromUtf8("unsexBtn"))
        self.label_10 = QtGui.QLabel(clamsLength)
        self.label_10.setGeometry(QtCore.QRect(609, 10, 162, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.picLabel = QtGui.QLabel(clamsLength)
        self.picLabel.setGeometry(QtCore.QRect(330, 10, 261, 196))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.picLabel.setFont(font)
        self.picLabel.setAutoFillBackground(True)
        self.picLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.picLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.picLabel.setText(_fromUtf8(""))
        self.picLabel.setObjectName(_fromUtf8("picLabel"))
        self.measureView = QtGui.QTableView(clamsLength)
        self.measureView.setGeometry(QtCore.QRect(680, 120, 321, 421))
        self.measureView.setObjectName(_fromUtf8("measureView"))
        self.measureView.verticalHeader().setVisible(False)
        self.lfPlot = QtGui.QGraphicsView(clamsLength)
        self.lfPlot.setGeometry(QtCore.QRect(20, 400, 451, 141))
        self.lfPlot.setObjectName(_fromUtf8("lfPlot"))

        self.retranslateUi(clamsLength)
        QtCore.QMetaObject.connectSlotsByName(clamsLength)

    def retranslateUi(self, clamsLength):
        clamsLength.setWindowTitle(_translate("clamsLength", "CLAMS Length", None))
        self.deleteBtn.setText(_translate("clamsLength", "Delete", None))
        self.doneBtn.setText(_translate("clamsLength", "Done", None))
        self.extraBtn_2.setText(_translate("clamsLength", "Show Plot", None))
        self.commentBtn.setText(_translate("clamsLength", "Comment", None))
        self.manualBtn.setText(_translate("clamsLength", "Manual Length", None))
        item = self.sumTable.verticalHeaderItem(0)
        item.setText(_translate("clamsLength", "Male", None))
        item = self.sumTable.verticalHeaderItem(1)
        item.setText(_translate("clamsLength", "Female", None))
        item = self.sumTable.verticalHeaderItem(2)
        item.setText(_translate("clamsLength", "Unsexed", None))
        item = self.sumTable.verticalHeaderItem(3)
        item.setText(_translate("clamsLength", "Total", None))
        self.label_3.setText(_translate("clamsLength", "Measurement values", None))
        self.label_4.setText(_translate("clamsLength", "Summary", None))
        self.label.setText(_translate("clamsLength", "Length type", None))
        self.label_2.setText(_translate("clamsLength", "Sampling Method", None))
        self.label_5.setText(_translate("clamsLength", "Species List", None))
        self.maleBtn.setText(_translate("clamsLength", "Male", None))
        self.femaleBtn.setText(_translate("clamsLength", "Female", None))
        self.unsexBtn.setText(_translate("clamsLength", "Unsexed", None))
        self.label_10.setText(_translate("clamsLength", "Today\'s Scientist", None))

