# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\CLAMSHaul.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_clamsHaul(object):
    def setupUi(self, clamsHaul):
        clamsHaul.setObjectName(_fromUtf8("clamsHaul"))
        clamsHaul.setEnabled(True)
        clamsHaul.resize(1020, 645)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(clamsHaul.sizePolicy().hasHeightForWidth())
        clamsHaul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        clamsHaul.setFont(font)
        self.label_2 = QtGui.QLabel(clamsHaul)
        self.label_2.setGeometry(QtCore.QRect(19, 23, 91, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.sciLabel = QtGui.QLabel(clamsHaul)
        self.sciLabel.setGeometry(QtCore.QRect(640, 10, 361, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sciLabel.setFont(font)
        self.sciLabel.setAutoFillBackground(True)
        self.sciLabel.setFrameShape(QtGui.QFrame.Panel)
        self.sciLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.sciLabel.setLineWidth(1)
        self.sciLabel.setText(_fromUtf8(""))
        self.sciLabel.setObjectName(_fromUtf8("sciLabel"))
        self.label_14 = QtGui.QLabel(clamsHaul)
        self.label_14.setGeometry(QtCore.QRect(491, 23, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.haulInfoLabelTop = QtGui.QLabel(clamsHaul)
        self.haulInfoLabelTop.setGeometry(QtCore.QRect(23, 161, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.haulInfoLabelTop.setFont(font)
        self.haulInfoLabelTop.setObjectName(_fromUtf8("haulInfoLabelTop"))
        self.groupBox_2 = QtGui.QGroupBox(clamsHaul)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 570, 981, 61))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.commentBtn = QtGui.QPushButton(self.groupBox_2)
        self.commentBtn.setGeometry(QtCore.QRect(660, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.commentBtn.setFont(font)
        self.commentBtn.setObjectName(_fromUtf8("commentBtn"))
        self.doneBtn = QtGui.QPushButton(self.groupBox_2)
        self.doneBtn.setGeometry(QtCore.QRect(830, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.accessLabel3 = QtGui.QLabel(clamsHaul)
        self.accessLabel3.setGeometry(QtCore.QRect(30, 269, 111, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.accessLabel3.setFont(font)
        self.accessLabel3.setText(_fromUtf8(""))
        self.accessLabel3.setObjectName(_fromUtf8("accessLabel3"))
        self.gearLabel = QtGui.QLabel(clamsHaul)
        self.gearLabel.setGeometry(QtCore.QRect(110, 10, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.gearLabel.setFont(font)
        self.gearLabel.setFrameShape(QtGui.QFrame.Box)
        self.gearLabel.setText(_fromUtf8(""))
        self.gearLabel.setObjectName(_fromUtf8("gearLabel"))
        self.picLabel = QtGui.QLabel(clamsHaul)
        self.picLabel.setGeometry(QtCore.QRect(690, 180, 301, 181))
        self.picLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.picLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.picLabel.setText(_fromUtf8(""))
        self.picLabel.setObjectName(_fromUtf8("picLabel"))
        self.label_6 = QtGui.QLabel(clamsHaul)
        self.label_6.setGeometry(QtCore.QRect(23, 70, 111, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.perfBox = QtGui.QComboBox(clamsHaul)
        self.perfBox.setEnabled(False)
        self.perfBox.setGeometry(QtCore.QRect(20, 100, 521, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.perfBox.setFont(font)
        self.perfBox.setObjectName(_fromUtf8("perfBox"))
        self.groupBox1 = QtGui.QGroupBox(clamsHaul)
        self.groupBox1.setGeometry(QtCore.QRect(200, 190, 151, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox1.setFont(font)
        self.groupBox1.setTitle(_fromUtf8(""))
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 29, 131, 321))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.haulInfoBtn1_1 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.haulInfoBtn1_1.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn1_1.setFont(font)
        self.haulInfoBtn1_1.setText(_fromUtf8(""))
        self.haulInfoBtn1_1.setObjectName(_fromUtf8("haulInfoBtn1_1"))
        self.verticalLayout.addWidget(self.haulInfoBtn1_1)
        self.haulInfoBtn1_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.haulInfoBtn1_2.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn1_2.setFont(font)
        self.haulInfoBtn1_2.setText(_fromUtf8(""))
        self.haulInfoBtn1_2.setObjectName(_fromUtf8("haulInfoBtn1_2"))
        self.verticalLayout.addWidget(self.haulInfoBtn1_2)
        self.haulInfoBtn1_3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.haulInfoBtn1_3.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn1_3.setFont(font)
        self.haulInfoBtn1_3.setText(_fromUtf8(""))
        self.haulInfoBtn1_3.setObjectName(_fromUtf8("haulInfoBtn1_3"))
        self.verticalLayout.addWidget(self.haulInfoBtn1_3)
        self.haulInfoBtn1_4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.haulInfoBtn1_4.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn1_4.setFont(font)
        self.haulInfoBtn1_4.setText(_fromUtf8(""))
        self.haulInfoBtn1_4.setObjectName(_fromUtf8("haulInfoBtn1_4"))
        self.verticalLayout.addWidget(self.haulInfoBtn1_4)
        self.groupBox2 = QtGui.QGroupBox(clamsHaul)
        self.groupBox2.setGeometry(QtCore.QRect(350, 190, 151, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox2.setFont(font)
        self.groupBox2.setTitle(_fromUtf8(""))
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 29, 131, 321))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.haulInfoBtn2_1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.haulInfoBtn2_1.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn2_1.setFont(font)
        self.haulInfoBtn2_1.setText(_fromUtf8(""))
        self.haulInfoBtn2_1.setObjectName(_fromUtf8("haulInfoBtn2_1"))
        self.verticalLayout_2.addWidget(self.haulInfoBtn2_1)
        self.haulInfoBtn2_2 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.haulInfoBtn2_2.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn2_2.setFont(font)
        self.haulInfoBtn2_2.setText(_fromUtf8(""))
        self.haulInfoBtn2_2.setObjectName(_fromUtf8("haulInfoBtn2_2"))
        self.verticalLayout_2.addWidget(self.haulInfoBtn2_2)
        self.haulInfoBtn2_3 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.haulInfoBtn2_3.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn2_3.setFont(font)
        self.haulInfoBtn2_3.setText(_fromUtf8(""))
        self.haulInfoBtn2_3.setObjectName(_fromUtf8("haulInfoBtn2_3"))
        self.verticalLayout_2.addWidget(self.haulInfoBtn2_3)
        self.haulInfoBtn2_4 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.haulInfoBtn2_4.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn2_4.setFont(font)
        self.haulInfoBtn2_4.setText(_fromUtf8(""))
        self.haulInfoBtn2_4.setObjectName(_fromUtf8("haulInfoBtn2_4"))
        self.verticalLayout_2.addWidget(self.haulInfoBtn2_4)
        self.groupBox3 = QtGui.QGroupBox(clamsHaul)
        self.groupBox3.setGeometry(QtCore.QRect(500, 190, 151, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox3.setFont(font)
        self.groupBox3.setTitle(_fromUtf8(""))
        self.groupBox3.setObjectName(_fromUtf8("groupBox3"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 29, 131, 321))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.haulInfoBtn3_1 = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.haulInfoBtn3_1.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn3_1.setFont(font)
        self.haulInfoBtn3_1.setText(_fromUtf8(""))
        self.haulInfoBtn3_1.setObjectName(_fromUtf8("haulInfoBtn3_1"))
        self.verticalLayout_4.addWidget(self.haulInfoBtn3_1)
        self.haulInfoBtn3_2 = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.haulInfoBtn3_2.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn3_2.setFont(font)
        self.haulInfoBtn3_2.setText(_fromUtf8(""))
        self.haulInfoBtn3_2.setObjectName(_fromUtf8("haulInfoBtn3_2"))
        self.verticalLayout_4.addWidget(self.haulInfoBtn3_2)
        self.haulInfoBtn3_3 = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.haulInfoBtn3_3.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn3_3.setFont(font)
        self.haulInfoBtn3_3.setText(_fromUtf8(""))
        self.haulInfoBtn3_3.setObjectName(_fromUtf8("haulInfoBtn3_3"))
        self.verticalLayout_4.addWidget(self.haulInfoBtn3_3)
        self.haulInfoBtn3_4 = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.haulInfoBtn3_4.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haulInfoBtn3_4.setFont(font)
        self.haulInfoBtn3_4.setText(_fromUtf8(""))
        self.haulInfoBtn3_4.setObjectName(_fromUtf8("haulInfoBtn3_4"))
        self.verticalLayout_4.addWidget(self.haulInfoBtn3_4)
        self.verticalLayoutWidget_5 = QtGui.QWidget(clamsHaul)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(29, 220, 171, 321))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.partitionLabel1 = QtGui.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partitionLabel1.sizePolicy().hasHeightForWidth())
        self.partitionLabel1.setSizePolicy(sizePolicy)
        self.partitionLabel1.setMinimumSize(QtCore.QSize(0, 51))
        self.partitionLabel1.setFrameShape(QtGui.QFrame.Box)
        self.partitionLabel1.setText(_fromUtf8(""))
        self.partitionLabel1.setObjectName(_fromUtf8("partitionLabel1"))
        self.verticalLayout_5.addWidget(self.partitionLabel1)
        self.partitionLabel2 = QtGui.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partitionLabel2.sizePolicy().hasHeightForWidth())
        self.partitionLabel2.setSizePolicy(sizePolicy)
        self.partitionLabel2.setMinimumSize(QtCore.QSize(0, 51))
        self.partitionLabel2.setFrameShape(QtGui.QFrame.Box)
        self.partitionLabel2.setText(_fromUtf8(""))
        self.partitionLabel2.setObjectName(_fromUtf8("partitionLabel2"))
        self.verticalLayout_5.addWidget(self.partitionLabel2)
        self.partitionLabel3 = QtGui.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partitionLabel3.sizePolicy().hasHeightForWidth())
        self.partitionLabel3.setSizePolicy(sizePolicy)
        self.partitionLabel3.setMinimumSize(QtCore.QSize(0, 51))
        self.partitionLabel3.setFrameShape(QtGui.QFrame.Box)
        self.partitionLabel3.setText(_fromUtf8(""))
        self.partitionLabel3.setObjectName(_fromUtf8("partitionLabel3"))
        self.verticalLayout_5.addWidget(self.partitionLabel3)
        self.partitionLabel4 = QtGui.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partitionLabel4.sizePolicy().hasHeightForWidth())
        self.partitionLabel4.setSizePolicy(sizePolicy)
        self.partitionLabel4.setMinimumSize(QtCore.QSize(0, 51))
        self.partitionLabel4.setFrameShape(QtGui.QFrame.Box)
        self.partitionLabel4.setText(_fromUtf8(""))
        self.partitionLabel4.setObjectName(_fromUtf8("partitionLabel4"))
        self.verticalLayout_5.addWidget(self.partitionLabel4)
        self.label_7 = QtGui.QLabel(clamsHaul)
        self.label_7.setGeometry(QtCore.QRect(72, 191, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.perfCheckBox = QtGui.QCheckBox(clamsHaul)
        self.perfCheckBox.setGeometry(QtCore.QRect(430, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.perfCheckBox.setFont(font)
        self.perfCheckBox.setObjectName(_fromUtf8("perfCheckBox"))

        self.retranslateUi(clamsHaul)
        QtCore.QMetaObject.connectSlotsByName(clamsHaul)

    def retranslateUi(self, clamsHaul):
        clamsHaul.setWindowTitle(_translate("clamsHaul", "CLAMS Haul", None))
        self.label_2.setText(_translate("clamsHaul", "Gear", None))
        self.label_14.setText(_translate("clamsHaul", "Today\'s Scientist", None))
        self.haulInfoLabelTop.setText(_translate("clamsHaul", "Haul Info", None))
        self.commentBtn.setText(_translate("clamsHaul", "Comment", None))
        self.doneBtn.setText(_translate("clamsHaul", "Done", None))
        self.label_6.setText(_translate("clamsHaul", "Performance", None))
        self.label_7.setText(_translate("clamsHaul", "Partitions", None))
        self.perfCheckBox.setText(_translate("clamsHaul", "Show All", None))

