# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\DeviceSetupDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_deviceSetupDlg(object):
    def setupUi(self, deviceSetupDlg):
        deviceSetupDlg.setObjectName(_fromUtf8("deviceSetupDlg"))
        deviceSetupDlg.resize(1020, 645)
        self.dn_1 = QtGui.QLabel(deviceSetupDlg)
        self.dn_1.setGeometry(QtCore.QRect(20, 100, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dn_1.setFont(font)
        self.dn_1.setFrameShape(QtGui.QFrame.Box)
        self.dn_1.setText(_fromUtf8(""))
        self.dn_1.setObjectName(_fromUtf8("dn_1"))
        self.dn_2 = QtGui.QLabel(deviceSetupDlg)
        self.dn_2.setGeometry(QtCore.QRect(20, 150, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dn_2.setFont(font)
        self.dn_2.setFrameShape(QtGui.QFrame.Box)
        self.dn_2.setText(_fromUtf8(""))
        self.dn_2.setObjectName(_fromUtf8("dn_2"))
        self.label_10 = QtGui.QLabel(deviceSetupDlg)
        self.label_10.setGeometry(QtCore.QRect(30, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(deviceSetupDlg)
        self.label_11.setGeometry(QtCore.QRect(210, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(deviceSetupDlg)
        self.label_12.setGeometry(QtCore.QRect(290, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(deviceSetupDlg)
        self.label_13.setGeometry(QtCore.QRect(380, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.sp_1 = QtGui.QComboBox(deviceSetupDlg)
        self.sp_1.setGeometry(QtCore.QRect(220, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sp_1.setFont(font)
        self.sp_1.setObjectName(_fromUtf8("sp_1"))
        self.br_1 = QtGui.QComboBox(deviceSetupDlg)
        self.br_1.setGeometry(QtCore.QRect(290, 100, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.br_1.setFont(font)
        self.br_1.setObjectName(_fromUtf8("br_1"))
        self.sf_1 = QtGui.QComboBox(deviceSetupDlg)
        self.sf_1.setGeometry(QtCore.QRect(380, 100, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sf_1.setFont(font)
        self.sf_1.setObjectName(_fromUtf8("sf_1"))
        self.label_14 = QtGui.QLabel(deviceSetupDlg)
        self.label_14.setGeometry(QtCore.QRect(580, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(deviceSetupDlg)
        self.label_15.setGeometry(QtCore.QRect(690, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(deviceSetupDlg)
        self.label_16.setGeometry(QtCore.QRect(780, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pt_1 = QtGui.QComboBox(deviceSetupDlg)
        self.pt_1.setGeometry(QtCore.QRect(580, 100, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pt_1.setFont(font)
        self.pt_1.setObjectName(_fromUtf8("pt_1"))
        self.addBtn = QtGui.QPushButton(deviceSetupDlg)
        self.addBtn.setGeometry(QtCore.QRect(20, 590, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName(_fromUtf8("addBtn"))
        self.removeBtn = QtGui.QPushButton(deviceSetupDlg)
        self.removeBtn.setGeometry(QtCore.QRect(180, 590, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.removeBtn.setFont(font)
        self.removeBtn.setObjectName(_fromUtf8("removeBtn"))
        self.pe_1 = QtGui.QLineEdit(deviceSetupDlg)
        self.pe_1.setGeometry(QtCore.QRect(780, 100, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pe_1.setFont(font)
        self.pe_1.setObjectName(_fromUtf8("pe_1"))
        self.pe_2 = QtGui.QLineEdit(deviceSetupDlg)
        self.pe_2.setGeometry(QtCore.QRect(780, 150, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pe_2.setFont(font)
        self.pe_2.setObjectName(_fromUtf8("pe_2"))
        self.br_2 = QtGui.QComboBox(deviceSetupDlg)
        self.br_2.setGeometry(QtCore.QRect(290, 150, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.br_2.setFont(font)
        self.br_2.setObjectName(_fromUtf8("br_2"))
        self.sp_2 = QtGui.QComboBox(deviceSetupDlg)
        self.sp_2.setGeometry(QtCore.QRect(220, 150, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sp_2.setFont(font)
        self.sp_2.setObjectName(_fromUtf8("sp_2"))
        self.sf_2 = QtGui.QComboBox(deviceSetupDlg)
        self.sf_2.setGeometry(QtCore.QRect(380, 150, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sf_2.setFont(font)
        self.sf_2.setObjectName(_fromUtf8("sf_2"))
        self.pt_2 = QtGui.QComboBox(deviceSetupDlg)
        self.pt_2.setGeometry(QtCore.QRect(580, 150, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pt_2.setFont(font)
        self.pt_2.setObjectName(_fromUtf8("pt_2"))
        self.br_3 = QtGui.QComboBox(deviceSetupDlg)
        self.br_3.setGeometry(QtCore.QRect(290, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.br_3.setFont(font)
        self.br_3.setObjectName(_fromUtf8("br_3"))
        self.dn_3 = QtGui.QLabel(deviceSetupDlg)
        self.dn_3.setGeometry(QtCore.QRect(20, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dn_3.setFont(font)
        self.dn_3.setFrameShape(QtGui.QFrame.Box)
        self.dn_3.setText(_fromUtf8(""))
        self.dn_3.setObjectName(_fromUtf8("dn_3"))
        self.sp_3 = QtGui.QComboBox(deviceSetupDlg)
        self.sp_3.setGeometry(QtCore.QRect(220, 200, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sp_3.setFont(font)
        self.sp_3.setObjectName(_fromUtf8("sp_3"))
        self.pe_3 = QtGui.QLineEdit(deviceSetupDlg)
        self.pe_3.setGeometry(QtCore.QRect(780, 200, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pe_3.setFont(font)
        self.pe_3.setObjectName(_fromUtf8("pe_3"))
        self.sf_3 = QtGui.QComboBox(deviceSetupDlg)
        self.sf_3.setGeometry(QtCore.QRect(380, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sf_3.setFont(font)
        self.sf_3.setObjectName(_fromUtf8("sf_3"))
        self.pt_3 = QtGui.QComboBox(deviceSetupDlg)
        self.pt_3.setGeometry(QtCore.QRect(580, 200, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pt_3.setFont(font)
        self.pt_3.setObjectName(_fromUtf8("pt_3"))
        self.br_4 = QtGui.QComboBox(deviceSetupDlg)
        self.br_4.setGeometry(QtCore.QRect(290, 250, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.br_4.setFont(font)
        self.br_4.setObjectName(_fromUtf8("br_4"))
        self.dn_4 = QtGui.QLabel(deviceSetupDlg)
        self.dn_4.setGeometry(QtCore.QRect(20, 250, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dn_4.setFont(font)
        self.dn_4.setFrameShape(QtGui.QFrame.Box)
        self.dn_4.setText(_fromUtf8(""))
        self.dn_4.setObjectName(_fromUtf8("dn_4"))
        self.sp_4 = QtGui.QComboBox(deviceSetupDlg)
        self.sp_4.setGeometry(QtCore.QRect(220, 250, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sp_4.setFont(font)
        self.sp_4.setObjectName(_fromUtf8("sp_4"))
        self.pe_4 = QtGui.QLineEdit(deviceSetupDlg)
        self.pe_4.setGeometry(QtCore.QRect(780, 250, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pe_4.setFont(font)
        self.pe_4.setObjectName(_fromUtf8("pe_4"))
        self.sf_4 = QtGui.QComboBox(deviceSetupDlg)
        self.sf_4.setGeometry(QtCore.QRect(380, 250, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sf_4.setFont(font)
        self.sf_4.setObjectName(_fromUtf8("sf_4"))
        self.pt_4 = QtGui.QComboBox(deviceSetupDlg)
        self.pt_4.setGeometry(QtCore.QRect(580, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pt_4.setFont(font)
        self.pt_4.setObjectName(_fromUtf8("pt_4"))
        self.br_5 = QtGui.QComboBox(deviceSetupDlg)
        self.br_5.setGeometry(QtCore.QRect(290, 300, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.br_5.setFont(font)
        self.br_5.setObjectName(_fromUtf8("br_5"))
        self.dn_5 = QtGui.QLabel(deviceSetupDlg)
        self.dn_5.setGeometry(QtCore.QRect(20, 300, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dn_5.setFont(font)
        self.dn_5.setFrameShape(QtGui.QFrame.Box)
        self.dn_5.setText(_fromUtf8(""))
        self.dn_5.setObjectName(_fromUtf8("dn_5"))
        self.sp_5 = QtGui.QComboBox(deviceSetupDlg)
        self.sp_5.setGeometry(QtCore.QRect(220, 300, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sp_5.setFont(font)
        self.sp_5.setObjectName(_fromUtf8("sp_5"))
        self.pe_5 = QtGui.QLineEdit(deviceSetupDlg)
        self.pe_5.setGeometry(QtCore.QRect(780, 300, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pe_5.setFont(font)
        self.pe_5.setObjectName(_fromUtf8("pe_5"))
        self.sf_5 = QtGui.QComboBox(deviceSetupDlg)
        self.sf_5.setGeometry(QtCore.QRect(380, 300, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sf_5.setFont(font)
        self.sf_5.setObjectName(_fromUtf8("sf_5"))
        self.pt_5 = QtGui.QComboBox(deviceSetupDlg)
        self.pt_5.setGeometry(QtCore.QRect(580, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pt_5.setFont(font)
        self.pt_5.setObjectName(_fromUtf8("pt_5"))
        self.br_6 = QtGui.QComboBox(deviceSetupDlg)
        self.br_6.setGeometry(QtCore.QRect(290, 350, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.br_6.setFont(font)
        self.br_6.setObjectName(_fromUtf8("br_6"))
        self.dn_6 = QtGui.QLabel(deviceSetupDlg)
        self.dn_6.setGeometry(QtCore.QRect(20, 350, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dn_6.setFont(font)
        self.dn_6.setFrameShape(QtGui.QFrame.Box)
        self.dn_6.setText(_fromUtf8(""))
        self.dn_6.setObjectName(_fromUtf8("dn_6"))
        self.sp_6 = QtGui.QComboBox(deviceSetupDlg)
        self.sp_6.setGeometry(QtCore.QRect(220, 350, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sp_6.setFont(font)
        self.sp_6.setObjectName(_fromUtf8("sp_6"))
        self.pe_6 = QtGui.QLineEdit(deviceSetupDlg)
        self.pe_6.setGeometry(QtCore.QRect(780, 350, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pe_6.setFont(font)
        self.pe_6.setObjectName(_fromUtf8("pe_6"))
        self.sf_6 = QtGui.QComboBox(deviceSetupDlg)
        self.sf_6.setGeometry(QtCore.QRect(380, 350, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sf_6.setFont(font)
        self.sf_6.setObjectName(_fromUtf8("sf_6"))
        self.pt_6 = QtGui.QComboBox(deviceSetupDlg)
        self.pt_6.setGeometry(QtCore.QRect(580, 350, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pt_6.setFont(font)
        self.pt_6.setObjectName(_fromUtf8("pt_6"))
        self.br_7 = QtGui.QComboBox(deviceSetupDlg)
        self.br_7.setGeometry(QtCore.QRect(290, 400, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.br_7.setFont(font)
        self.br_7.setObjectName(_fromUtf8("br_7"))
        self.dn_7 = QtGui.QLabel(deviceSetupDlg)
        self.dn_7.setGeometry(QtCore.QRect(20, 400, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dn_7.setFont(font)
        self.dn_7.setFrameShape(QtGui.QFrame.Box)
        self.dn_7.setText(_fromUtf8(""))
        self.dn_7.setObjectName(_fromUtf8("dn_7"))
        self.sp_7 = QtGui.QComboBox(deviceSetupDlg)
        self.sp_7.setGeometry(QtCore.QRect(220, 400, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sp_7.setFont(font)
        self.sp_7.setObjectName(_fromUtf8("sp_7"))
        self.pe_7 = QtGui.QLineEdit(deviceSetupDlg)
        self.pe_7.setGeometry(QtCore.QRect(780, 400, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pe_7.setFont(font)
        self.pe_7.setObjectName(_fromUtf8("pe_7"))
        self.sf_7 = QtGui.QComboBox(deviceSetupDlg)
        self.sf_7.setGeometry(QtCore.QRect(380, 400, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sf_7.setFont(font)
        self.sf_7.setObjectName(_fromUtf8("sf_7"))
        self.pt_7 = QtGui.QComboBox(deviceSetupDlg)
        self.pt_7.setGeometry(QtCore.QRect(580, 400, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pt_7.setFont(font)
        self.pt_7.setObjectName(_fromUtf8("pt_7"))
        self.doneBtn = QtGui.QPushButton(deviceSetupDlg)
        self.doneBtn.setGeometry(QtCore.QRect(860, 590, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.label = QtGui.QLabel(deviceSetupDlg)
        self.label.setGeometry(QtCore.QRect(30, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(deviceSetupDlg)
        self.label_2.setGeometry(QtCore.QRect(460, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ws = QtGui.QLabel(deviceSetupDlg)
        self.ws.setGeometry(QtCore.QRect(190, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ws.setFont(font)
        self.ws.setFrameShape(QtGui.QFrame.Box)
        self.ws.setText(_fromUtf8(""))
        self.ws.setObjectName(_fromUtf8("ws"))
        self.hn = QtGui.QLabel(deviceSetupDlg)
        self.hn.setGeometry(QtCore.QRect(600, 10, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hn.setFont(font)
        self.hn.setFrameShape(QtGui.QFrame.Box)
        self.hn.setText(_fromUtf8(""))
        self.hn.setObjectName(_fromUtf8("hn"))
        self.pi_1 = QtGui.QLineEdit(deviceSetupDlg)
        self.pi_1.setGeometry(QtCore.QRect(690, 100, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pi_1.setFont(font)
        self.pi_1.setObjectName(_fromUtf8("pi_1"))
        self.pi_2 = QtGui.QLineEdit(deviceSetupDlg)
        self.pi_2.setGeometry(QtCore.QRect(690, 150, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pi_2.setFont(font)
        self.pi_2.setObjectName(_fromUtf8("pi_2"))
        self.pi_3 = QtGui.QLineEdit(deviceSetupDlg)
        self.pi_3.setGeometry(QtCore.QRect(690, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pi_3.setFont(font)
        self.pi_3.setObjectName(_fromUtf8("pi_3"))
        self.pi_4 = QtGui.QLineEdit(deviceSetupDlg)
        self.pi_4.setGeometry(QtCore.QRect(690, 250, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pi_4.setFont(font)
        self.pi_4.setObjectName(_fromUtf8("pi_4"))
        self.pi_5 = QtGui.QLineEdit(deviceSetupDlg)
        self.pi_5.setGeometry(QtCore.QRect(690, 300, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pi_5.setFont(font)
        self.pi_5.setObjectName(_fromUtf8("pi_5"))
        self.pi_6 = QtGui.QLineEdit(deviceSetupDlg)
        self.pi_6.setGeometry(QtCore.QRect(690, 350, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pi_6.setFont(font)
        self.pi_6.setObjectName(_fromUtf8("pi_6"))
        self.pi_7 = QtGui.QLineEdit(deviceSetupDlg)
        self.pi_7.setGeometry(QtCore.QRect(690, 400, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pi_7.setFont(font)
        self.pi_7.setObjectName(_fromUtf8("pi_7"))
        self.testBtn = QtGui.QPushButton(deviceSetupDlg)
        self.testBtn.setGeometry(QtCore.QRect(340, 590, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.testBtn.setFont(font)
        self.testBtn.setObjectName(_fromUtf8("testBtn"))
        self.plainTextEdit = QtGui.QPlainTextEdit(deviceSetupDlg)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 470, 601, 111))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.label_17 = QtGui.QLabel(deviceSetupDlg)
        self.label_17.setGeometry(QtCore.QRect(20, 446, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))

        self.retranslateUi(deviceSetupDlg)
        QtCore.QMetaObject.connectSlotsByName(deviceSetupDlg)

    def retranslateUi(self, deviceSetupDlg):
        deviceSetupDlg.setWindowTitle(_translate("deviceSetupDlg", "CLAMS Length", None))
        self.label_10.setText(_translate("deviceSetupDlg", "Device Name", None))
        self.label_11.setText(_translate("deviceSetupDlg", "Serial Port", None))
        self.label_12.setText(_translate("deviceSetupDlg", "Baud Rate", None))
        self.label_13.setText(_translate("deviceSetupDlg", "Sound File", None))
        self.label_14.setText(_translate("deviceSetupDlg", "Parse Type", None))
        self.label_15.setText(_translate("deviceSetupDlg", "Parse Index", None))
        self.label_16.setText(_translate("deviceSetupDlg", "Parse Expression", None))
        self.addBtn.setText(_translate("deviceSetupDlg", "Add Device", None))
        self.removeBtn.setText(_translate("deviceSetupDlg", "Remove Device", None))
        self.doneBtn.setText(_translate("deviceSetupDlg", "Done", None))
        self.label.setText(_translate("deviceSetupDlg", "Work Station", None))
        self.label_2.setText(_translate("deviceSetupDlg", "Host Name", None))
        self.testBtn.setText(_translate("deviceSetupDlg", "Test", None))
        self.label_17.setText(_translate("deviceSetupDlg", "Log Window", None))

