# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CLAMS\ui\xga\ExtendedSampleCollection.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_extendedsamplecollectionDlg(object):
    def setupUi(self, extendedsamplecollectionDlg):
        extendedsamplecollectionDlg.setObjectName(_fromUtf8("extendedsamplecollectionDlg"))
        extendedsamplecollectionDlg.resize(880, 597)
        self.gridLayout_2 = QtGui.QGridLayout(extendedsamplecollectionDlg)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(extendedsamplecollectionDlg)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Btn5 = QtGui.QPushButton(self.groupBox)
        self.Btn5.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn5.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn5.setFont(font)
        self.Btn5.setText(_fromUtf8(""))
        self.Btn5.setCheckable(True)
        self.Btn5.setObjectName(_fromUtf8("Btn5"))
        self.gridLayout.addWidget(self.Btn5, 3, 0, 1, 1)
        self.Btn11 = QtGui.QPushButton(self.groupBox)
        self.Btn11.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn11.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn11.setFont(font)
        self.Btn11.setText(_fromUtf8(""))
        self.Btn11.setCheckable(True)
        self.Btn11.setObjectName(_fromUtf8("Btn11"))
        self.gridLayout.addWidget(self.Btn11, 5, 2, 1, 1)
        self.Btn1 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn1.sizePolicy().hasHeightForWidth())
        self.Btn1.setSizePolicy(sizePolicy)
        self.Btn1.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn1.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn1.setFont(font)
        self.Btn1.setText(_fromUtf8(""))
        self.Btn1.setCheckable(True)
        self.Btn1.setObjectName(_fromUtf8("Btn1"))
        self.gridLayout.addWidget(self.Btn1, 1, 0, 1, 1)
        self.Btn4 = QtGui.QPushButton(self.groupBox)
        self.Btn4.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn4.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn4.setFont(font)
        self.Btn4.setText(_fromUtf8(""))
        self.Btn4.setCheckable(True)
        self.Btn4.setObjectName(_fromUtf8("Btn4"))
        self.gridLayout.addWidget(self.Btn4, 1, 3, 1, 1)
        self.Btn6 = QtGui.QPushButton(self.groupBox)
        self.Btn6.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn6.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn6.setFont(font)
        self.Btn6.setText(_fromUtf8(""))
        self.Btn6.setCheckable(True)
        self.Btn6.setObjectName(_fromUtf8("Btn6"))
        self.gridLayout.addWidget(self.Btn6, 3, 1, 1, 1)
        self.Btn3 = QtGui.QPushButton(self.groupBox)
        self.Btn3.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn3.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn3.setFont(font)
        self.Btn3.setText(_fromUtf8(""))
        self.Btn3.setCheckable(True)
        self.Btn3.setObjectName(_fromUtf8("Btn3"))
        self.gridLayout.addWidget(self.Btn3, 1, 2, 1, 1)
        self.Btn2 = QtGui.QPushButton(self.groupBox)
        self.Btn2.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn2.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn2.setFont(font)
        self.Btn2.setText(_fromUtf8(""))
        self.Btn2.setCheckable(True)
        self.Btn2.setObjectName(_fromUtf8("Btn2"))
        self.gridLayout.addWidget(self.Btn2, 1, 1, 1, 1)
        self.Btn8 = QtGui.QPushButton(self.groupBox)
        self.Btn8.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn8.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn8.setFont(font)
        self.Btn8.setText(_fromUtf8(""))
        self.Btn8.setCheckable(True)
        self.Btn8.setObjectName(_fromUtf8("Btn8"))
        self.gridLayout.addWidget(self.Btn8, 3, 3, 1, 1)
        self.Btn9 = QtGui.QPushButton(self.groupBox)
        self.Btn9.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn9.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn9.setFont(font)
        self.Btn9.setText(_fromUtf8(""))
        self.Btn9.setCheckable(True)
        self.Btn9.setObjectName(_fromUtf8("Btn9"))
        self.gridLayout.addWidget(self.Btn9, 5, 0, 1, 1)
        self.doneBtn = QtGui.QPushButton(self.groupBox)
        self.doneBtn.setMinimumSize(QtCore.QSize(200, 100))
        self.doneBtn.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.gridLayout.addWidget(self.doneBtn, 6, 3, 1, 1)
        self.Btn7 = QtGui.QPushButton(self.groupBox)
        self.Btn7.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn7.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn7.setFont(font)
        self.Btn7.setText(_fromUtf8(""))
        self.Btn7.setCheckable(True)
        self.Btn7.setObjectName(_fromUtf8("Btn7"))
        self.gridLayout.addWidget(self.Btn7, 3, 2, 1, 1)
        self.clearBtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearBtn.sizePolicy().hasHeightForWidth())
        self.clearBtn.setSizePolicy(sizePolicy)
        self.clearBtn.setMinimumSize(QtCore.QSize(200, 100))
        self.clearBtn.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName(_fromUtf8("clearBtn"))
        self.gridLayout.addWidget(self.clearBtn, 6, 2, 1, 1)
        self.Btn12 = QtGui.QPushButton(self.groupBox)
        self.Btn12.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn12.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn12.setFont(font)
        self.Btn12.setText(_fromUtf8(""))
        self.Btn12.setCheckable(True)
        self.Btn12.setObjectName(_fromUtf8("Btn12"))
        self.gridLayout.addWidget(self.Btn12, 5, 3, 1, 1)
        self.Btn14 = QtGui.QPushButton(self.groupBox)
        self.Btn14.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn14.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn14.setFont(font)
        self.Btn14.setText(_fromUtf8(""))
        self.Btn14.setCheckable(True)
        self.Btn14.setObjectName(_fromUtf8("Btn14"))
        self.gridLayout.addWidget(self.Btn14, 6, 1, 1, 1)
        self.Btn13 = QtGui.QPushButton(self.groupBox)
        self.Btn13.setMinimumSize(QtCore.QSize(100, 0))
        self.Btn13.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn13.setFont(font)
        self.Btn13.setText(_fromUtf8(""))
        self.Btn13.setCheckable(True)
        self.Btn13.setObjectName(_fromUtf8("Btn13"))
        self.gridLayout.addWidget(self.Btn13, 6, 0, 1, 1)
        self.Btn10 = QtGui.QPushButton(self.groupBox)
        self.Btn10.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn10.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn10.setFont(font)
        self.Btn10.setText(_fromUtf8(""))
        self.Btn10.setCheckable(True)
        self.Btn10.setObjectName(_fromUtf8("Btn10"))
        self.gridLayout.addWidget(self.Btn10, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(extendedsamplecollectionDlg)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)

        self.retranslateUi(extendedsamplecollectionDlg)
        QtCore.QMetaObject.connectSlotsByName(extendedsamplecollectionDlg)

    def retranslateUi(self, extendedsamplecollectionDlg):
        extendedsamplecollectionDlg.setWindowTitle(_translate("extendedsamplecollectionDlg", "Special Studies", None))
        self.doneBtn.setText(_translate("extendedsamplecollectionDlg", "Done", None))
        self.clearBtn.setText(_translate("extendedsamplecollectionDlg", "Clear", None))
        self.label_3.setText(_translate("extendedsamplecollectionDlg", "Optional Special Studies", None))

