# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\LoadCellDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_loadcellDialog(object):
    def setupUi(self, loadcellDialog):
        loadcellDialog.setObjectName(_fromUtf8("loadcellDialog"))
        loadcellDialog.setEnabled(True)
        loadcellDialog.resize(488, 254)
        self.grossLabel = QtGui.QLabel(loadcellDialog)
        self.grossLabel.setGeometry(QtCore.QRect(320, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.grossLabel.setFont(font)
        self.grossLabel.setAutoFillBackground(True)
        self.grossLabel.setFrameShape(QtGui.QFrame.Box)
        self.grossLabel.setLineWidth(2)
        self.grossLabel.setText(_fromUtf8(""))
        self.grossLabel.setObjectName(_fromUtf8("grossLabel"))
        self.tareLabel = QtGui.QLabel(loadcellDialog)
        self.tareLabel.setGeometry(QtCore.QRect(320, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tareLabel.setFont(font)
        self.tareLabel.setAutoFillBackground(True)
        self.tareLabel.setFrameShape(QtGui.QFrame.Box)
        self.tareLabel.setLineWidth(2)
        self.tareLabel.setText(_fromUtf8(""))
        self.tareLabel.setObjectName(_fromUtf8("tareLabel"))
        self.haulWtLabel = QtGui.QLabel(loadcellDialog)
        self.haulWtLabel.setGeometry(QtCore.QRect(320, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.haulWtLabel.setFont(font)
        self.haulWtLabel.setAutoFillBackground(True)
        self.haulWtLabel.setFrameShape(QtGui.QFrame.Box)
        self.haulWtLabel.setLineWidth(2)
        self.haulWtLabel.setText(_fromUtf8(""))
        self.haulWtLabel.setObjectName(_fromUtf8("haulWtLabel"))
        self.line = QtGui.QFrame(loadcellDialog)
        self.line.setGeometry(QtCore.QRect(20, 120, 461, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.okBtn = QtGui.QPushButton(loadcellDialog)
        self.okBtn.setEnabled(False)
        self.okBtn.setGeometry(QtCore.QRect(310, 190, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName(_fromUtf8("okBtn"))
        self.cancelBtn = QtGui.QPushButton(loadcellDialog)
        self.cancelBtn.setGeometry(QtCore.QRect(140, 190, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.grossBtn = QtGui.QPushButton(loadcellDialog)
        self.grossBtn.setGeometry(QtCore.QRect(320, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.grossBtn.setFont(font)
        self.grossBtn.setText(_fromUtf8(""))
        self.grossBtn.setAutoDefault(False)
        self.grossBtn.setFlat(True)
        self.grossBtn.setObjectName(_fromUtf8("grossBtn"))
        self.tareBtn = QtGui.QPushButton(loadcellDialog)
        self.tareBtn.setEnabled(False)
        self.tareBtn.setGeometry(QtCore.QRect(320, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tareBtn.setFont(font)
        self.tareBtn.setText(_fromUtf8(""))
        self.tareBtn.setAutoDefault(False)
        self.tareBtn.setFlat(True)
        self.tareBtn.setObjectName(_fromUtf8("tareBtn"))
        self.groupBox = QtGui.QGroupBox(loadcellDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 190, 114, 47))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioKg = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioKg.setFont(font)
        self.radioKg.setChecked(True)
        self.radioKg.setObjectName(_fromUtf8("radioKg"))
        self.horizontalLayout.addWidget(self.radioKg)
        self.radioLb = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioLb.setFont(font)
        self.radioLb.setObjectName(_fromUtf8("radioLb"))
        self.horizontalLayout.addWidget(self.radioLb)
        self.label = QtGui.QLabel(loadcellDialog)
        self.label.setGeometry(QtCore.QRect(20, 140, 173, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(loadcellDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(loadcellDialog)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))

        self.retranslateUi(loadcellDialog)
        QtCore.QMetaObject.connectSlotsByName(loadcellDialog)

    def retranslateUi(self, loadcellDialog):
        loadcellDialog.setWindowTitle(_translate("loadcellDialog", "Load Cell", None))
        self.okBtn.setText(_translate("loadcellDialog", "OK", None))
        self.cancelBtn.setText(_translate("loadcellDialog", "Cancel", None))
        self.radioKg.setText(_translate("loadcellDialog", "Kg", None))
        self.radioLb.setText(_translate("loadcellDialog", "Lb", None))
        self.label.setText(_translate("loadcellDialog", "Haul Weight", None))
        self.label_2.setText(_translate("loadcellDialog", "Gross Weight", None))
        self.label_3.setText(_translate("loadcellDialog", "Tare Weight", None))

