# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\MatGuide.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_matGuide(object):
    def setupUi(self, matGuide):
        matGuide.setObjectName(_fromUtf8("matGuide"))
        matGuide.resize(1020, 645)
        self.groupBox = QtGui.QGroupBox(matGuide)
        self.groupBox.setGeometry(QtCore.QRect(100, 220, 191, 411))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.mat1Btn = QtGui.QPushButton(self.groupBox)
        self.mat1Btn.setGeometry(QtCore.QRect(10, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat1Btn.setFont(font)
        self.mat1Btn.setCheckable(True)
        self.mat1Btn.setAutoExclusive(True)
        self.mat1Btn.setObjectName(_fromUtf8("mat1Btn"))
        self.mat2Btn = QtGui.QPushButton(self.groupBox)
        self.mat2Btn.setGeometry(QtCore.QRect(10, 60, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat2Btn.setFont(font)
        self.mat2Btn.setCheckable(True)
        self.mat2Btn.setAutoExclusive(True)
        self.mat2Btn.setObjectName(_fromUtf8("mat2Btn"))
        self.mat3Btn = QtGui.QPushButton(self.groupBox)
        self.mat3Btn.setGeometry(QtCore.QRect(10, 110, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat3Btn.setFont(font)
        self.mat3Btn.setCheckable(True)
        self.mat3Btn.setAutoExclusive(True)
        self.mat3Btn.setObjectName(_fromUtf8("mat3Btn"))
        self.mat4Btn = QtGui.QPushButton(self.groupBox)
        self.mat4Btn.setGeometry(QtCore.QRect(10, 160, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat4Btn.setFont(font)
        self.mat4Btn.setCheckable(True)
        self.mat4Btn.setAutoExclusive(True)
        self.mat4Btn.setObjectName(_fromUtf8("mat4Btn"))
        self.mat8Btn = QtGui.QPushButton(self.groupBox)
        self.mat8Btn.setGeometry(QtCore.QRect(10, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat8Btn.setFont(font)
        self.mat8Btn.setCheckable(True)
        self.mat8Btn.setAutoExclusive(True)
        self.mat8Btn.setObjectName(_fromUtf8("mat8Btn"))
        self.mat7Btn = QtGui.QPushButton(self.groupBox)
        self.mat7Btn.setGeometry(QtCore.QRect(10, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat7Btn.setFont(font)
        self.mat7Btn.setCheckable(True)
        self.mat7Btn.setAutoExclusive(True)
        self.mat7Btn.setObjectName(_fromUtf8("mat7Btn"))
        self.mat6Btn = QtGui.QPushButton(self.groupBox)
        self.mat6Btn.setGeometry(QtCore.QRect(10, 260, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat6Btn.setFont(font)
        self.mat6Btn.setCheckable(True)
        self.mat6Btn.setAutoExclusive(True)
        self.mat6Btn.setObjectName(_fromUtf8("mat6Btn"))
        self.mat5Btn = QtGui.QPushButton(self.groupBox)
        self.mat5Btn.setGeometry(QtCore.QRect(10, 210, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mat5Btn.setFont(font)
        self.mat5Btn.setCheckable(True)
        self.mat5Btn.setAutoExclusive(True)
        self.mat5Btn.setObjectName(_fromUtf8("mat5Btn"))
        self.groupBox_2 = QtGui.QGroupBox(matGuide)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 100, 191, 111))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.femaleBtn = QtGui.QPushButton(self.groupBox_2)
        self.femaleBtn.setGeometry(QtCore.QRect(10, 60, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.femaleBtn.setFont(font)
        self.femaleBtn.setCheckable(True)
        self.femaleBtn.setAutoExclusive(True)
        self.femaleBtn.setObjectName(_fromUtf8("femaleBtn"))
        self.maleBtn = QtGui.QPushButton(self.groupBox_2)
        self.maleBtn.setGeometry(QtCore.QRect(10, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maleBtn.setFont(font)
        self.maleBtn.setCheckable(True)
        self.maleBtn.setChecked(True)
        self.maleBtn.setAutoExclusive(True)
        self.maleBtn.setObjectName(_fromUtf8("maleBtn"))
        self.picLabel = QtGui.QLabel(matGuide)
        self.picLabel.setGeometry(QtCore.QRect(300, 10, 691, 461))
        self.picLabel.setAutoFillBackground(True)
        self.picLabel.setFrameShape(QtGui.QFrame.Box)
        self.picLabel.setText(_fromUtf8(""))
        self.picLabel.setObjectName(_fromUtf8("picLabel"))
        self.descLabel = QtGui.QLabel(matGuide)
        self.descLabel.setGeometry(QtCore.QRect(300, 470, 691, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.descLabel.setFont(font)
        self.descLabel.setAutoFillBackground(True)
        self.descLabel.setFrameShape(QtGui.QFrame.Box)
        self.descLabel.setText(_fromUtf8(""))
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName(_fromUtf8("descLabel"))
        self.groupBox_3 = QtGui.QGroupBox(matGuide)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 560, 691, 71))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.exitBtn = QtGui.QPushButton(self.groupBox_3)
        self.exitBtn.setGeometry(QtCore.QRect(530, 10, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName(_fromUtf8("exitBtn"))
        self.nextBtn = QtGui.QPushButton(self.groupBox_3)
        self.nextBtn.setGeometry(QtCore.QRect(270, 10, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.prevBtn = QtGui.QPushButton(self.groupBox_3)
        self.prevBtn.setGeometry(QtCore.QRect(10, 10, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.prevBtn.setFont(font)
        self.prevBtn.setObjectName(_fromUtf8("prevBtn"))
        self.spcLabel = QtGui.QLabel(matGuide)
        self.spcLabel.setGeometry(QtCore.QRect(20, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spcLabel.setFont(font)
        self.spcLabel.setAutoFillBackground(True)
        self.spcLabel.setText(_fromUtf8(""))
        self.spcLabel.setObjectName(_fromUtf8("spcLabel"))
        self.matTabLabel = QtGui.QLabel(matGuide)
        self.matTabLabel.setGeometry(QtCore.QRect(190, 50, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.matTabLabel.setFont(font)
        self.matTabLabel.setAcceptDrops(True)
        self.matTabLabel.setAutoFillBackground(True)
        self.matTabLabel.setText(_fromUtf8(""))
        self.matTabLabel.setObjectName(_fromUtf8("matTabLabel"))
        self.label_6 = QtGui.QLabel(matGuide)
        self.label_6.setGeometry(QtCore.QRect(20, 370, 69, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(matGuide)
        self.label_5.setGeometry(QtCore.QRect(30, 400, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(matGuide)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(matGuide)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(matGuide)
        self.label.setGeometry(QtCore.QRect(30, 60, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(matGuide)
        QtCore.QMetaObject.connectSlotsByName(matGuide)

    def retranslateUi(self, matGuide):
        matGuide.setWindowTitle(_translate("matGuide", "Maturity Guide", None))
        self.mat1Btn.setText(_translate("matGuide", "PushButton", None))
        self.mat2Btn.setText(_translate("matGuide", "PushButton", None))
        self.mat3Btn.setText(_translate("matGuide", "PushButton", None))
        self.mat4Btn.setText(_translate("matGuide", "PushButton", None))
        self.mat8Btn.setText(_translate("matGuide", "PushButton", None))
        self.mat7Btn.setText(_translate("matGuide", "PushButton", None))
        self.mat6Btn.setText(_translate("matGuide", "PushButton", None))
        self.mat5Btn.setText(_translate("matGuide", "PushButton", None))
        self.femaleBtn.setText(_translate("matGuide", "Female", None))
        self.maleBtn.setText(_translate("matGuide", "Male", None))
        self.exitBtn.setText(_translate("matGuide", "Done", None))
        self.nextBtn.setText(_translate("matGuide", "Next Image", None))
        self.prevBtn.setText(_translate("matGuide", "Previous Image", None))
        self.label_6.setText(_translate("matGuide", "Maturity", None))
        self.label_5.setText(_translate("matGuide", "Stage", None))
        self.label_2.setText(_translate("matGuide", "Fish", None))
        self.label_4.setText(_translate("matGuide", "Sex", None))
        self.label.setText(_translate("matGuide", "Maturity Table ", None))

