# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\NewSurveyDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_newSurveyDlg(object):
    def setupUi(self, newSurveyDlg):
        newSurveyDlg.setObjectName(_fromUtf8("newSurveyDlg"))
        newSurveyDlg.resize(530, 603)
        self.verticalLayout = QtGui.QVBoxLayout(newSurveyDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_12 = QtGui.QLabel(newSurveyDlg)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.frame_2 = QtGui.QFrame(newSurveyDlg)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout = QtGui.QFormLayout(self.frame_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.cbShip = QtGui.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cbShip.setFont(font)
        self.cbShip.setObjectName(_fromUtf8("cbShip"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbShip)
        self.label_10 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.surveyNumEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.surveyNumEdit.setFont(font)
        self.surveyNumEdit.setObjectName(_fromUtf8("surveyNumEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.surveyNumEdit)
        self.label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.surveyNameEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.surveyNameEdit.setFont(font)
        self.surveyNameEdit.setObjectName(_fromUtf8("surveyNameEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.surveyNameEdit)
        self.label_9 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_3 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_3)
        self.startDateEdit = QtGui.QDateEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startDateEdit.setFont(font)
        self.startDateEdit.setObjectName(_fromUtf8("startDateEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.startDateEdit)
        self.label_4 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_4)
        self.endDateEdit = QtGui.QDateEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.endDateEdit.setFont(font)
        self.endDateEdit.setObjectName(_fromUtf8("endDateEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.endDateEdit)
        self.label_5 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_8)
        self.cbSeaArea = QtGui.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cbSeaArea.setFont(font)
        self.cbSeaArea.setObjectName(_fromUtf8("cbSeaArea"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.cbSeaArea)
        self.label_7 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cbRegion = QtGui.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cbRegion.setFont(font)
        self.cbRegion.setObjectName(_fromUtf8("cbRegion"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.cbRegion)
        self.label_11 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_11)
        self.abstractEdit = QtGui.QPlainTextEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.abstractEdit.setFont(font)
        self.abstractEdit.setObjectName(_fromUtf8("abstractEdit"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.abstractEdit)
        self.cbChiefSci = QtGui.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cbChiefSci.setFont(font)
        self.cbChiefSci.setObjectName(_fromUtf8("cbChiefSci"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cbChiefSci)
        self.cbEndPort = QtGui.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cbEndPort.setFont(font)
        self.cbEndPort.setObjectName(_fromUtf8("cbEndPort"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.cbEndPort)
        self.cbStartPort = QtGui.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cbStartPort.setFont(font)
        self.cbStartPort.setObjectName(_fromUtf8("cbStartPort"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.cbStartPort)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame = QtGui.QFrame(newSurveyDlg)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.createBtn = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.createBtn.setFont(font)
        self.createBtn.setObjectName(_fromUtf8("createBtn"))
        self.horizontalLayout.addWidget(self.createBtn)
        self.cancelBtn = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(newSurveyDlg)
        QtCore.QMetaObject.connectSlotsByName(newSurveyDlg)

    def retranslateUi(self, newSurveyDlg):
        newSurveyDlg.setWindowTitle(_translate("newSurveyDlg", "Create New Survey", None))
        self.label_12.setText(_translate("newSurveyDlg", "Create New Survey", None))
        self.label.setText(_translate("newSurveyDlg", "Ship", None))
        self.label_10.setText(_translate("newSurveyDlg", "Survey Number (YYYYNN)", None))
        self.surveyNumEdit.setToolTip(_translate("newSurveyDlg", "<html><head/><body><p>Year and cruise number typically in the form YYYYNN where YYYY is the year and NN is the cruise number. Example: 201608</p></body></html>", None))
        self.label_2.setText(_translate("newSurveyDlg", "Survey Name", None))
        self.label_9.setText(_translate("newSurveyDlg", "Chief Scientist", None))
        self.label_3.setText(_translate("newSurveyDlg", "Start Date", None))
        self.label_4.setText(_translate("newSurveyDlg", "End Date", None))
        self.label_5.setText(_translate("newSurveyDlg", "Start Port", None))
        self.label_6.setText(_translate("newSurveyDlg", "End Port", None))
        self.label_8.setText(_translate("newSurveyDlg", "Abstract", None))
        self.cbSeaArea.setToolTip(_translate("newSurveyDlg", "<html><head/><body><p>The IHO sea area where the majority of the survey took place.</p></body></html>", None))
        self.label_7.setText(_translate("newSurveyDlg", "Sea Area", None))
        self.cbRegion.setToolTip(_translate("newSurveyDlg", "<html><head/><body><p>The region the survey took place. This is used primarily in the creation of the survey title in the metadata exports from the database. </p></body></html>", None))
        self.label_11.setText(_translate("newSurveyDlg", "Region", None))
        self.abstractEdit.setToolTip(_translate("newSurveyDlg", "<html><head/><body><p>The description of the survey. This is used as the survey description in the metadata export. Often it is completed post survey.</p></body></html>", None))
        self.createBtn.setText(_translate("newSurveyDlg", "Create Survey", None))
        self.cancelBtn.setText(_translate("newSurveyDlg", "Cancel", None))

