# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\NoiseAnalysis.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(874, 601)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Spectrogram_Widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Spectrogram_Widget.sizePolicy().hasHeightForWidth())
        self.Spectrogram_Widget.setSizePolicy(sizePolicy)
        self.Spectrogram_Widget.setObjectName(_fromUtf8("Spectrogram_Widget"))
        self.gridLayout.addWidget(self.Spectrogram_Widget, 1, 0, 1, 1)
        self.Time_Series_Widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Time_Series_Widget.sizePolicy().hasHeightForWidth())
        self.Time_Series_Widget.setSizePolicy(sizePolicy)
        self.Time_Series_Widget.setMinimumSize(QtCore.QSize(400, 0))
        self.Time_Series_Widget.setObjectName(_fromUtf8("Time_Series_Widget"))
        self.gridLayout.addWidget(self.Time_Series_Widget, 0, 0, 1, 1)
        self.Spectrum_and_SPL_Widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Spectrum_and_SPL_Widget.sizePolicy().hasHeightForWidth())
        self.Spectrum_and_SPL_Widget.setSizePolicy(sizePolicy)
        self.Spectrum_and_SPL_Widget.setObjectName(_fromUtf8("Spectrum_and_SPL_Widget"))
        self.Time_Series_Widget.raise_()
        self.gridLayout.addWidget(self.Spectrum_and_SPL_Widget, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 2, 2, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 4)
        self.Run_button = QtGui.QPushButton(self.centralwidget)
        self.Run_button.setObjectName(_fromUtf8("Run_button"))
        self.gridLayout_2.addWidget(self.Run_button, 0, 9, 1, 4)
        self.Lat_deg_box = QtGui.QLineEdit(self.centralwidget)
        self.Lat_deg_box.setObjectName(_fromUtf8("Lat_deg_box"))
        self.gridLayout_2.addWidget(self.Lat_deg_box, 6, 3, 1, 4)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 3, 12, 1, 1)
        self.Nfft_spin_box = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Nfft_spin_box.setFont(font)
        self.Nfft_spin_box.setObjectName(_fromUtf8("Nfft_spin_box"))
        self.gridLayout_2.addWidget(self.Nfft_spin_box, 2, 10, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 10, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.Browse_button = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Browse_button.sizePolicy().hasHeightForWidth())
        self.Browse_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Browse_button.setFont(font)
        self.Browse_button.setObjectName(_fromUtf8("Browse_button"))
        self.gridLayout_2.addWidget(self.Browse_button, 0, 0, 1, 9)
        self.Time_spin_box = QtGui.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Time_spin_box.setFont(font)
        self.Time_spin_box.setObjectName(_fromUtf8("Time_spin_box"))
        self.gridLayout_2.addWidget(self.Time_spin_box, 2, 5, 1, 3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 8, 1, 2)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 3)
        self.Date_box = QtGui.QLineEdit(self.centralwidget)
        self.Date_box.setObjectName(_fromUtf8("Date_box"))
        self.gridLayout_2.addWidget(self.Date_box, 3, 3, 1, 5)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 3, 8, 1, 2)
        self.Time_box = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Time_box.setFont(font)
        self.Time_box.setObjectName(_fromUtf8("Time_box"))
        self.gridLayout_2.addWidget(self.Time_box, 3, 10, 1, 2)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 5, 0, 1, 5)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 3)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 6, 7, 1, 6)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 3)
        self.Lon_deg_box = QtGui.QLineEdit(self.centralwidget)
        self.Lon_deg_box.setObjectName(_fromUtf8("Lon_deg_box"))
        self.gridLayout_2.addWidget(self.Lon_deg_box, 7, 3, 1, 4)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 7, 7, 1, 6)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 8, 0, 1, 3)
        self.Shaft_box = QtGui.QLineEdit(self.centralwidget)
        self.Shaft_box.setObjectName(_fromUtf8("Shaft_box"))
        self.gridLayout_2.addWidget(self.Shaft_box, 8, 3, 1, 4)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 9, 0, 1, 3)
        self.Speed_box = QtGui.QLineEdit(self.centralwidget)
        self.Speed_box.setObjectName(_fromUtf8("Speed_box"))
        self.gridLayout_2.addWidget(self.Speed_box, 9, 3, 1, 4)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 11, 0, 1, 2)
        self.Comment_box = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Comment_box.sizePolicy().hasHeightForWidth())
        self.Comment_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Comment_box.setFont(font)
        self.Comment_box.setObjectName(_fromUtf8("Comment_box"))
        self.gridLayout_2.addWidget(self.Comment_box, 11, 2, 1, 11)
        self.Write_button = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Write_button.sizePolicy().hasHeightForWidth())
        self.Write_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Write_button.setFont(font)
        self.Write_button.setObjectName(_fromUtf8("Write_button"))
        self.gridLayout_2.addWidget(self.Write_button, 12, 0, 1, 13)
        self.Filename_button = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Filename_button.sizePolicy().hasHeightForWidth())
        self.Filename_button.setSizePolicy(sizePolicy)
        self.Filename_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Filename_button.setObjectName(_fromUtf8("Filename_button"))
        self.gridLayout_2.addWidget(self.Filename_button, 1, 0, 1, 13)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Time to Analyze (s)", None))
        self.Run_button.setText(_translate("MainWindow", "Process Data", None))
        self.label_15.setText(_translate("MainWindow", "UTC", None))
        self.Browse_button.setText(_translate("MainWindow", "Browse File", None))
        self.label_2.setText(_translate("MainWindow", "Nfft", None))
        self.label_6.setText(_translate("MainWindow", "Date (YYYYMMDD)", None))
        self.label_8.setText(_translate("MainWindow", "Time (HHMM)", None))
        self.label_16.setText(_translate("MainWindow", "Vessel Parameters", None))
        self.label_7.setText(_translate("MainWindow", "Latitude", None))
        self.label_11.setText(_translate("MainWindow", "in Decimal Minutes (e.g., 56 45.189)", None))
        self.label_9.setText(_translate("MainWindow", "Longitude", None))
        self.label_13.setText(_translate("MainWindow", "in Decimal Minutes (e.g., 156 54.859)", None))
        self.label_3.setText(_translate("MainWindow", "Shaft speed (RPM)", None))
        self.label_4.setText(_translate("MainWindow", "SOG (knots)", None))
        self.label_5.setText(_translate("MainWindow", "Noise Comments", None))
        self.Write_button.setText(_translate("MainWindow", "Write to log file", None))
        self.Filename_button.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">File chosen</span></p></body></html>", None))

