# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\NetDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_netDlg(object):
    def setupUi(self, netDlg):
        netDlg.setObjectName(_fromUtf8("netDlg"))
        netDlg.resize(608, 640)
        self.verticalLayout = QtGui.QVBoxLayout(netDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setMargin(2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(netDlg)
        self.label_4.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.btn1 = QtGui.QPushButton(netDlg)
        self.btn1.setMinimumSize(QtCore.QSize(250, 0))
        self.btn1.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn1.setFont(font)
        self.btn1.setText(_fromUtf8(""))
        self.btn1.setFlat(False)
        self.btn1.setObjectName(_fromUtf8("btn1"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.btn1)
        self.label_5 = QtGui.QLabel(netDlg)
        self.label_5.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.btn2 = QtGui.QPushButton(netDlg)
        self.btn2.setMinimumSize(QtCore.QSize(250, 0))
        self.btn2.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn2.setFont(font)
        self.btn2.setText(_fromUtf8(""))
        self.btn2.setObjectName(_fromUtf8("btn2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.btn2)
        self.label_6 = QtGui.QLabel(netDlg)
        self.label_6.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.btn3 = QtGui.QPushButton(netDlg)
        self.btn3.setMinimumSize(QtCore.QSize(250, 0))
        self.btn3.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn3.setFont(font)
        self.btn3.setText(_fromUtf8(""))
        self.btn3.setObjectName(_fromUtf8("btn3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.btn3)
        self.label_8 = QtGui.QLabel(netDlg)
        self.label_8.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.btn4 = QtGui.QPushButton(netDlg)
        self.btn4.setMinimumSize(QtCore.QSize(250, 0))
        self.btn4.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn4.setFont(font)
        self.btn4.setText(_fromUtf8(""))
        self.btn4.setObjectName(_fromUtf8("btn4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.btn4)
        self.verticalLayout.addLayout(self.formLayout)
        self.label = QtGui.QLabel(netDlg)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.netTable = QtGui.QTableWidget(netDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.netTable.setFont(font)
        self.netTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.netTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.netTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.netTable.setObjectName(_fromUtf8("netTable"))
        self.netTable.setColumnCount(5)
        self.netTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.netTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.netTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.netTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.netTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.netTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.netTable)
        self.groupBox = QtGui.QGroupBox(netDlg)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.deleteBtn = QtGui.QPushButton(self.groupBox)
        self.deleteBtn.setEnabled(True)
        self.deleteBtn.setMinimumSize(QtCore.QSize(150, 64))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName(_fromUtf8("deleteBtn"))
        self.horizontalLayout.addWidget(self.deleteBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addRecordBtn = QtGui.QPushButton(self.groupBox)
        self.addRecordBtn.setMinimumSize(QtCore.QSize(150, 64))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addRecordBtn.setFont(font)
        self.addRecordBtn.setObjectName(_fromUtf8("addRecordBtn"))
        self.horizontalLayout.addWidget(self.addRecordBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.okBtn = QtGui.QPushButton(self.groupBox)
        self.okBtn.setMinimumSize(QtCore.QSize(150, 64))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName(_fromUtf8("okBtn"))
        self.horizontalLayout.addWidget(self.okBtn)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(netDlg)
        QtCore.QMetaObject.connectSlotsByName(netDlg)

    def retranslateUi(self, netDlg):
        netDlg.setWindowTitle(_translate("netDlg", "Net Mensuration Dialog", None))
        self.label_4.setText(_translate("netDlg", "Net Height", None))
        self.label_5.setText(_translate("netDlg", "Net Width", None))
        self.label_6.setText(_translate("netDlg", "Headrope Depth", None))
        self.label_8.setText(_translate("netDlg", "Wire Out", None))
        item = self.netTable.horizontalHeaderItem(0)
        item.setText(_translate("netDlg", "Time", None))
        item = self.netTable.horizontalHeaderItem(1)
        item.setText(_translate("netDlg", "Height", None))
        item = self.netTable.horizontalHeaderItem(2)
        item.setText(_translate("netDlg", "Width", None))
        item = self.netTable.horizontalHeaderItem(3)
        item.setText(_translate("netDlg", "Depth", None))
        item = self.netTable.horizontalHeaderItem(4)
        item.setText(_translate("netDlg", "Wire Out", None))
        self.deleteBtn.setText(_translate("netDlg", "Delete \n"
"Record", None))
        self.addRecordBtn.setText(_translate("netDlg", "Add\n"
" Record", None))
        self.okBtn.setText(_translate("netDlg", "Done", None))

