# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\NumPad.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_numpad(object):
    def setupUi(self, numpad):
        numpad.setObjectName(_fromUtf8("numpad"))
        numpad.setWindowModality(QtCore.Qt.WindowModal)
        numpad.resize(401, 518)
        self.groupBox = QtGui.QGroupBox(numpad)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 381, 311))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pBtn1 = QtGui.QPushButton(self.groupBox)
        self.pBtn1.setGeometry(QtCore.QRect(10, 10, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn1.setFont(font)
        self.pBtn1.setObjectName(_fromUtf8("pBtn1"))
        self.pBtn2 = QtGui.QPushButton(self.groupBox)
        self.pBtn2.setGeometry(QtCore.QRect(130, 10, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn2.setFont(font)
        self.pBtn2.setObjectName(_fromUtf8("pBtn2"))
        self.pBtn3 = QtGui.QPushButton(self.groupBox)
        self.pBtn3.setGeometry(QtCore.QRect(250, 10, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn3.setFont(font)
        self.pBtn3.setObjectName(_fromUtf8("pBtn3"))
        self.pBtn6 = QtGui.QPushButton(self.groupBox)
        self.pBtn6.setGeometry(QtCore.QRect(250, 80, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn6.setFont(font)
        self.pBtn6.setObjectName(_fromUtf8("pBtn6"))
        self.pBtn5 = QtGui.QPushButton(self.groupBox)
        self.pBtn5.setGeometry(QtCore.QRect(130, 80, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn5.setFont(font)
        self.pBtn5.setObjectName(_fromUtf8("pBtn5"))
        self.pBtn4 = QtGui.QPushButton(self.groupBox)
        self.pBtn4.setGeometry(QtCore.QRect(10, 80, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn4.setFont(font)
        self.pBtn4.setObjectName(_fromUtf8("pBtn4"))
        self.pBtn9 = QtGui.QPushButton(self.groupBox)
        self.pBtn9.setGeometry(QtCore.QRect(250, 150, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn9.setFont(font)
        self.pBtn9.setObjectName(_fromUtf8("pBtn9"))
        self.pBtn7 = QtGui.QPushButton(self.groupBox)
        self.pBtn7.setGeometry(QtCore.QRect(10, 150, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn7.setFont(font)
        self.pBtn7.setObjectName(_fromUtf8("pBtn7"))
        self.pBtn8 = QtGui.QPushButton(self.groupBox)
        self.pBtn8.setGeometry(QtCore.QRect(130, 150, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn8.setFont(font)
        self.pBtn8.setObjectName(_fromUtf8("pBtn8"))
        self.pBtnClr = QtGui.QPushButton(self.groupBox)
        self.pBtnClr.setGeometry(QtCore.QRect(10, 220, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pBtnClr.setFont(font)
        self.pBtnClr.setObjectName(_fromUtf8("pBtnClr"))
        self.pBtnd = QtGui.QPushButton(self.groupBox)
        self.pBtnd.setGeometry(QtCore.QRect(250, 220, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnd.setFont(font)
        self.pBtnd.setObjectName(_fromUtf8("pBtnd"))
        self.pBtn0 = QtGui.QPushButton(self.groupBox)
        self.pBtn0.setGeometry(QtCore.QRect(130, 220, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn0.setFont(font)
        self.pBtn0.setObjectName(_fromUtf8("pBtn0"))
        self.pBtnEnt = QtGui.QPushButton(numpad)
        self.pBtnEnt.setGeometry(QtCore.QRect(20, 440, 361, 70))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pBtnEnt.setFont(font)
        self.pBtnEnt.setObjectName(_fromUtf8("pBtnEnt"))
        self.dispBox = QtGui.QLabel(numpad)
        self.dispBox.setGeometry(QtCore.QRect(10, 50, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.dispBox.setFont(font)
        self.dispBox.setAutoFillBackground(True)
        self.dispBox.setFrameShape(QtGui.QFrame.WinPanel)
        self.dispBox.setFrameShadow(QtGui.QFrame.Plain)
        self.dispBox.setText(_fromUtf8(""))
        self.dispBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispBox.setObjectName(_fromUtf8("dispBox"))
        self.msgLabel = QtGui.QLabel(numpad)
        self.msgLabel.setGeometry(QtCore.QRect(20, 13, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.msgLabel.setFont(font)
        self.msgLabel.setText(_fromUtf8(""))
        self.msgLabel.setObjectName(_fromUtf8("msgLabel"))

        self.retranslateUi(numpad)
        QtCore.QMetaObject.connectSlotsByName(numpad)

    def retranslateUi(self, numpad):
        numpad.setWindowTitle(_translate("numpad", "NumPad", None))
        self.pBtn1.setText(_translate("numpad", "1", None))
        self.pBtn2.setText(_translate("numpad", "2", None))
        self.pBtn3.setText(_translate("numpad", "3", None))
        self.pBtn6.setText(_translate("numpad", "6", None))
        self.pBtn5.setText(_translate("numpad", "5", None))
        self.pBtn4.setText(_translate("numpad", "4", None))
        self.pBtn9.setText(_translate("numpad", "9", None))
        self.pBtn7.setText(_translate("numpad", "7", None))
        self.pBtn8.setText(_translate("numpad", "8", None))
        self.pBtnClr.setText(_translate("numpad", "Clear", None))
        self.pBtnd.setText(_translate("numpad", ".", None))
        self.pBtn0.setText(_translate("numpad", "0", None))
        self.pBtnEnt.setText(_translate("numpad", "Enter", None))

