# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\Desktop\CLAMS\ui\xga\SubCalcDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_subcalcDlg(object):
    def setupUi(self, subcalcDlg):
        subcalcDlg.setObjectName(_fromUtf8("subcalcDlg"))
        subcalcDlg.resize(353, 472)
        self.answerLabel = QtGui.QLabel(subcalcDlg)
        self.answerLabel.setGeometry(QtCore.QRect(20, 320, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.answerLabel.setFont(font)
        self.answerLabel.setAutoFillBackground(True)
        self.answerLabel.setFrameShape(QtGui.QFrame.Box)
        self.answerLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.answerLabel.setText(_fromUtf8(""))
        self.answerLabel.setObjectName(_fromUtf8("answerLabel"))
        self.numLabel = QtGui.QLabel(subcalcDlg)
        self.numLabel.setGeometry(QtCore.QRect(230, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.numLabel.setFont(font)
        self.numLabel.setAutoFillBackground(True)
        self.numLabel.setFrameShape(QtGui.QFrame.Box)
        self.numLabel.setText(_fromUtf8(""))
        self.numLabel.setObjectName(_fromUtf8("numLabel"))
        self.catchWtLabel = QtGui.QLabel(subcalcDlg)
        self.catchWtLabel.setGeometry(QtCore.QRect(230, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.catchWtLabel.setFont(font)
        self.catchWtLabel.setAutoFillBackground(True)
        self.catchWtLabel.setFrameShape(QtGui.QFrame.Box)
        self.catchWtLabel.setText(_fromUtf8(""))
        self.catchWtLabel.setObjectName(_fromUtf8("catchWtLabel"))
        self.wtLabel = QtGui.QLabel(subcalcDlg)
        self.wtLabel.setGeometry(QtCore.QRect(230, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.wtLabel.setFont(font)
        self.wtLabel.setAutoFillBackground(True)
        self.wtLabel.setFrameShape(QtGui.QFrame.Box)
        self.wtLabel.setText(_fromUtf8(""))
        self.wtLabel.setObjectName(_fromUtf8("wtLabel"))
        self.samplenumLabel = QtGui.QLabel(subcalcDlg)
        self.samplenumLabel.setGeometry(QtCore.QRect(230, 220, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.samplenumLabel.setFont(font)
        self.samplenumLabel.setAutoFillBackground(True)
        self.samplenumLabel.setFrameShape(QtGui.QFrame.Box)
        self.samplenumLabel.setObjectName(_fromUtf8("samplenumLabel"))
        self.okBtn = QtGui.QPushButton(subcalcDlg)
        self.okBtn.setGeometry(QtCore.QRect(40, 400, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName(_fromUtf8("okBtn"))
        self.remindCheck = QtGui.QCheckBox(subcalcDlg)
        self.remindCheck.setEnabled(True)
        self.remindCheck.setGeometry(QtCore.QRect(200, 320, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.remindCheck.setFont(font)
        self.remindCheck.setObjectName(_fromUtf8("remindCheck"))
        self.wtBtn = QtGui.QPushButton(subcalcDlg)
        self.wtBtn.setGeometry(QtCore.QRect(10, 40, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wtBtn.setFont(font)
        self.wtBtn.setObjectName(_fromUtf8("wtBtn"))
        self.numBtn = QtGui.QPushButton(subcalcDlg)
        self.numBtn.setGeometry(QtCore.QRect(10, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numBtn.setFont(font)
        self.numBtn.setObjectName(_fromUtf8("numBtn"))
        self.catchWtBtn = QtGui.QPushButton(subcalcDlg)
        self.catchWtBtn.setGeometry(QtCore.QRect(10, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.catchWtBtn.setFont(font)
        self.catchWtBtn.setObjectName(_fromUtf8("catchWtBtn"))
        self.samplenumBtn = QtGui.QPushButton(subcalcDlg)
        self.samplenumBtn.setGeometry(QtCore.QRect(10, 220, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.samplenumBtn.setFont(font)
        self.samplenumBtn.setObjectName(_fromUtf8("samplenumBtn"))
        self.label = QtGui.QLabel(subcalcDlg)
        self.label.setGeometry(QtCore.QRect(20, 290, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(subcalcDlg)
        self.label_2.setGeometry(QtCore.QRect(100, 330, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(subcalcDlg)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 323, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cancelBtn = QtGui.QPushButton(subcalcDlg)
        self.cancelBtn.setGeometry(QtCore.QRect(190, 400, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))

        self.retranslateUi(subcalcDlg)
        QtCore.QMetaObject.connectSlotsByName(subcalcDlg)

    def retranslateUi(self, subcalcDlg):
        subcalcDlg.setWindowTitle(_translate("subcalcDlg", "subsample calculator", None))
        self.samplenumLabel.setText(_translate("subcalcDlg", "300", None))
        self.okBtn.setText(_translate("subcalcDlg", "OK", None))
        self.remindCheck.setText(_translate("subcalcDlg", "Remind me!", None))
        self.wtBtn.setText(_translate("subcalcDlg", "Weight of Test Basket", None))
        self.numBtn.setText(_translate("subcalcDlg", "Fish in Test Basket", None))
        self.catchWtBtn.setText(_translate("subcalcDlg", "Weight of Catch", None))
        self.samplenumBtn.setText(_translate("subcalcDlg", "Fish to be Sampled", None))
        self.label.setText(_translate("subcalcDlg", "You need to keep every ", None))
        self.label_2.setText(_translate("subcalcDlg", "-th basket", None))
        self.label_3.setText(_translate("subcalcDlg", "Please enter details from a Test Basket", None))
        self.cancelBtn.setText(_translate("subcalcDlg", "Cancel", None))

