# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rtowler\AFSCsvn\CLAMS\trunk\application\acquisition\serial\ui\SerialFaker.ui'
#
# Created: Wed Nov 10 11:01:01 2010
#      by: PyQt4 UI code generator 4.8
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SerialFaker(object):
    def setupUi(self, SerialFaker):
        SerialFaker.setObjectName(_fromUtf8("SerialFaker"))
        SerialFaker.resize(681, 242)
        self.centralwidget = QtGui.QWidget(SerialFaker)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lengthText = QtGui.QLineEdit(self.centralwidget)
        self.lengthText.setGeometry(QtCore.QRect(180, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lengthText.setFont(font)
        self.lengthText.setObjectName(_fromUtf8("lengthText"))
        self.smallScaleText = QtGui.QLineEdit(self.centralwidget)
        self.smallScaleText.setGeometry(QtCore.QRect(180, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.smallScaleText.setFont(font)
        self.smallScaleText.setObjectName(_fromUtf8("smallScaleText"))
        self.largeScaleText = QtGui.QLineEdit(self.centralwidget)
        self.largeScaleText.setGeometry(QtCore.QRect(180, 150, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.largeScaleText.setFont(font)
        self.largeScaleText.setObjectName(_fromUtf8("largeScaleText"))
        self.barCodeText = QtGui.QLineEdit(self.centralwidget)
        self.barCodeText.setGeometry(QtCore.QRect(180, 200, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.barCodeText.setFont(font)
        self.barCodeText.setObjectName(_fromUtf8("barCodeText"))
        self.sendBtn1 = QtGui.QPushButton(self.centralwidget)
        self.sendBtn1.setGeometry(QtCore.QRect(380, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendBtn1.setFont(font)
        self.sendBtn1.setObjectName(_fromUtf8("sendBtn1"))
        self.sendBtn2 = QtGui.QPushButton(self.centralwidget)
        self.sendBtn2.setGeometry(QtCore.QRect(380, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendBtn2.setFont(font)
        self.sendBtn2.setObjectName(_fromUtf8("sendBtn2"))
        self.sendBtn3 = QtGui.QPushButton(self.centralwidget)
        self.sendBtn3.setGeometry(QtCore.QRect(380, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendBtn3.setFont(font)
        self.sendBtn3.setObjectName(_fromUtf8("sendBtn3"))
        self.sendBtn4 = QtGui.QPushButton(self.centralwidget)
        self.sendBtn4.setGeometry(QtCore.QRect(380, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendBtn4.setFont(font)
        self.sendBtn4.setObjectName(_fromUtf8("sendBtn4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 10, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.fileBtn1 = QtGui.QPushButton(self.centralwidget)
        self.fileBtn1.setGeometry(QtCore.QRect(540, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fileBtn1.setFont(font)
        self.fileBtn1.setObjectName(_fromUtf8("fileBtn1"))
        SerialFaker.setCentralWidget(self.centralwidget)
        self.actionConfigure_Ports = QtGui.QAction(SerialFaker)
        self.actionConfigure_Ports.setObjectName(_fromUtf8("actionConfigure_Ports"))

        self.retranslateUi(SerialFaker)
        QtCore.QMetaObject.connectSlotsByName(SerialFaker)

    def retranslateUi(self, SerialFaker):
        SerialFaker.setWindowTitle(QtGui.QApplication.translate("SerialFaker", "Don\'t make it, fake it", None, QtGui.QApplication.UnicodeUTF8))
        self.sendBtn1.setText(QtGui.QApplication.translate("SerialFaker", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.sendBtn2.setText(QtGui.QApplication.translate("SerialFaker", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.sendBtn3.setText(QtGui.QApplication.translate("SerialFaker", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.sendBtn4.setText(QtGui.QApplication.translate("SerialFaker", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SerialFaker", "Serial Faker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SerialFaker", "Length Board", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SerialFaker", "Small Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SerialFaker", "Large scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SerialFaker", "Barcode", None, QtGui.QApplication.UnicodeUTF8))
        self.fileBtn1.setText(QtGui.QApplication.translate("SerialFaker", "file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure_Ports.setText(QtGui.QApplication.translate("SerialFaker", "Configure Ports...", None, QtGui.QApplication.UnicodeUTF8))

