# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rick.towler\AFSCGit\CamTrawl\Client\DropCamViewer\acquisition\serial\ui\SelectWinPortDialog.ui'
#
# Created: Fri Jun 26 13:11:37 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SelectWinPortDialog(object):
    def setupUi(self, SelectWinPortDialog):
        SelectWinPortDialog.setObjectName(_fromUtf8("SelectWinPortDialog"))
        SelectWinPortDialog.setWindowModality(QtCore.Qt.NonModal)
        SelectWinPortDialog.resize(505, 191)
        SelectWinPortDialog.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SelectWinPortDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.titleLabel = QtGui.QLabel(SelectWinPortDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(SelectWinPortDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cbPorts = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbPorts.setFont(font)
        self.cbPorts.setObjectName(_fromUtf8("cbPorts"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbPorts)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.cbBaud = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbBaud.setFont(font)
        self.cbBaud.setMaxVisibleItems(6)
        self.cbBaud.setObjectName(_fromUtf8("cbBaud"))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.cbBaud.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbBaud)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(SelectWinPortDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.descLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.descLabel.setFont(font)
        self.descLabel.setText(_fromUtf8(""))
        self.descLabel.setObjectName(_fromUtf8("descLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.descLabel)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        self.label_5.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.idLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.idLabel.setFont(font)
        self.idLabel.setText(_fromUtf8(""))
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.idLabel)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(110, 0))
        self.label.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.statusLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statusLabel.setFont(font)
        self.statusLabel.setText(_fromUtf8(""))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.statusLabel)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pbOK = QtGui.QPushButton(SelectWinPortDialog)
        self.pbOK.setObjectName(_fromUtf8("pbOK"))
        self.horizontalLayout_3.addWidget(self.pbOK)
        self.pbCancel = QtGui.QPushButton(SelectWinPortDialog)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.horizontalLayout_3.addWidget(self.pbCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(SelectWinPortDialog)
        self.cbBaud.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SelectWinPortDialog)

    def retranslateUi(self, SelectWinPortDialog):
        SelectWinPortDialog.setWindowTitle(_translate("SelectWinPortDialog", "Select COM port", None))
        self.titleLabel.setText(_translate("SelectWinPortDialog", "Select a COM Port", None))
        self.groupBox_2.setTitle(_translate("SelectWinPortDialog", "COM Port", None))
        self.label_4.setText(_translate("SelectWinPortDialog", "Port", None))
        self.label_8.setText(_translate("SelectWinPortDialog", "Baud", None))
        self.cbBaud.setItemText(0, _translate("SelectWinPortDialog", "1200", None))
        self.cbBaud.setItemText(1, _translate("SelectWinPortDialog", "2400", None))
        self.cbBaud.setItemText(2, _translate("SelectWinPortDialog", "4800", None))
        self.cbBaud.setItemText(3, _translate("SelectWinPortDialog", "9600", None))
        self.cbBaud.setItemText(4, _translate("SelectWinPortDialog", "19200", None))
        self.cbBaud.setItemText(5, _translate("SelectWinPortDialog", "31250", None))
        self.cbBaud.setItemText(6, _translate("SelectWinPortDialog", "38400", None))
        self.cbBaud.setItemText(7, _translate("SelectWinPortDialog", "57600", None))
        self.cbBaud.setItemText(8, _translate("SelectWinPortDialog", "115200", None))
        self.cbBaud.setItemText(9, _translate("SelectWinPortDialog", "230400", None))
        self.groupBox.setTitle(_translate("SelectWinPortDialog", "COM Port Details", None))
        self.label_3.setText(_translate("SelectWinPortDialog", "Description:", None))
        self.label_5.setText(_translate("SelectWinPortDialog", "Hardware ID:", None))
        self.label.setText(_translate("SelectWinPortDialog", "Status:", None))
        self.pbOK.setText(_translate("SelectWinPortDialog", "OK", None))
        self.pbCancel.setText(_translate("SelectWinPortDialog", "Cancel", None))

