# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\AdminDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_admindlg(object):
    def setupUi(self, admindlg):
        admindlg.setObjectName("admindlg")
        admindlg.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(admindlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(admindlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.createSurveyBtn = QtWidgets.QPushButton(admindlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.createSurveyBtn.setFont(font)
        self.createSurveyBtn.setObjectName("createSurveyBtn")
        self.verticalLayout.addWidget(self.createSurveyBtn)
        self.selectSurveyBtn = QtWidgets.QPushButton(admindlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.selectSurveyBtn.setFont(font)
        self.selectSurveyBtn.setObjectName("selectSurveyBtn")
        self.verticalLayout.addWidget(self.selectSurveyBtn)
        self.setupBtn = QtWidgets.QPushButton(admindlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.setupBtn.setFont(font)
        self.setupBtn.setObjectName("setupBtn")
        self.verticalLayout.addWidget(self.setupBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.doneBtn = QtWidgets.QPushButton(admindlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.verticalLayout.addWidget(self.doneBtn)

        self.retranslateUi(admindlg)
        QtCore.QMetaObject.connectSlotsByName(admindlg)

    def retranslateUi(self, admindlg):
        _translate = QtCore.QCoreApplication.translate
        admindlg.setWindowTitle(_translate("admindlg", "CLAMS Administration"))
        self.label.setText(_translate("admindlg", "CLAMS Administration"))
        self.createSurveyBtn.setText(_translate("admindlg", "Create Survey"))
        self.selectSurveyBtn.setText(_translate("admindlg", "Change Active Survey"))
        self.setupBtn.setText(_translate("admindlg", "Edit and Setup"))
        self.doneBtn.setText(_translate("admindlg", "Done"))
