# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\BasketEditDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_basketeditDlg(object):
    def setupUi(self, basketeditDlg):
        basketeditDlg.setObjectName("basketeditDlg")
        basketeditDlg.resize(533, 238)
        self.okBtn = QtWidgets.QPushButton(basketeditDlg)
        self.okBtn.setGeometry(QtCore.QRect(300, 170, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.cancelBtn = QtWidgets.QPushButton(basketeditDlg)
        self.cancelBtn.setGeometry(QtCore.QRect(20, 170, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.label = QtWidgets.QLabel(basketeditDlg)
        self.label.setGeometry(QtCore.QRect(20, 15, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.editBasket = QtWidgets.QTableWidget(basketeditDlg)
        self.editBasket.setGeometry(QtCore.QRect(20, 40, 501, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editBasket.setFont(font)
        self.editBasket.setObjectName("editBasket")
        self.editBasket.setColumnCount(0)
        self.editBasket.setRowCount(0)

        self.retranslateUi(basketeditDlg)
        QtCore.QMetaObject.connectSlotsByName(basketeditDlg)

    def retranslateUi(self, basketeditDlg):
        _translate = QtCore.QCoreApplication.translate
        basketeditDlg.setWindowTitle(_translate("basketeditDlg", "Edit"))
        self.okBtn.setText(_translate("basketeditDlg", "OK"))
        self.cancelBtn.setText(_translate("basketeditDlg", "Cancel"))
        self.label.setText(_translate("basketeditDlg", "Select field to edit ..."))
