# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CLAMS-Python-x64\CLAMS\ui\CLAMSsbeDownloader.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sbeDownloader(object):
    def setupUi(self, sbeDownloader):
        sbeDownloader.setObjectName(_fromUtf8("sbeDownloader"))
        sbeDownloader.resize(690, 556)
        sbeDownloader.setMinimumSize(QtCore.QSize(690, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        sbeDownloader.setFont(font)
        self.centralwidget = QtGui.QWidget(sbeDownloader)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.shipLabel = QtGui.QLineEdit(self.centralwidget)
        self.shipLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shipLabel.setFont(font)
        self.shipLabel.setReadOnly(True)
        self.shipLabel.setObjectName(_fromUtf8("shipLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.shipLabel)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.surveyLabel = QtGui.QLineEdit(self.centralwidget)
        self.surveyLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.surveyLabel.setFont(font)
        self.surveyLabel.setReadOnly(True)
        self.surveyLabel.setObjectName(_fromUtf8("surveyLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.surveyLabel)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.haulLabel = QtGui.QLineEdit(self.centralwidget)
        self.haulLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.haulLabel.setFont(font)
        self.haulLabel.setObjectName(_fromUtf8("haulLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.haulLabel)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.imgLabel = QtGui.QLabel(self.centralwidget)
        self.imgLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.imgLabel.setTextFormat(QtCore.Qt.AutoText)
        self.imgLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.imgLabel.setObjectName(_fromUtf8("imgLabel"))
        self.horizontalLayout_3.addWidget(self.imgLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_34 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_2.addWidget(self.label_34)
        self.dataText = QtGui.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(11)
        self.dataText.setFont(font)
        self.dataText.setObjectName(_fromUtf8("dataText"))
        self.verticalLayout_2.addWidget(self.dataText)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.connectButton = QtGui.QPushButton(self.centralwidget)
        self.connectButton.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.connectButton.setFont(font)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.verticalLayout_3.addWidget(self.connectButton)
        self.downloadButton = QtGui.QPushButton(self.centralwidget)
        self.downloadButton.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.downloadButton.setFont(font)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.verticalLayout_3.addWidget(self.downloadButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startButton.setFont(font)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.verticalLayout_5.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.verticalLayout_5.addWidget(self.stopButton)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.statusButton = QtGui.QPushButton(self.centralwidget)
        self.statusButton.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusButton.setFont(font)
        self.statusButton.setObjectName(_fromUtf8("statusButton"))
        self.verticalLayout_6.addWidget(self.statusButton)
        self.doneBtn = QtGui.QPushButton(self.centralwidget)
        self.doneBtn.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.verticalLayout_6.addWidget(self.doneBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        sbeDownloader.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(sbeDownloader)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        sbeDownloader.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(sbeDownloader)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 690, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuConfigure = QtGui.QMenu(self.menuBar)
        self.menuConfigure.setObjectName(_fromUtf8("menuConfigure"))
        sbeDownloader.setMenuBar(self.menuBar)
        self.actionExit = QtGui.QAction(sbeDownloader)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSetInterval = QtGui.QAction(sbeDownloader)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionSetInterval.setFont(font)
        self.actionSetInterval.setObjectName(_fromUtf8("actionSetInterval"))
        self.actionSetComPort = QtGui.QAction(sbeDownloader)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionSetComPort.setFont(font)
        self.actionSetComPort.setObjectName(_fromUtf8("actionSetComPort"))
        self.actionSetSurvey = QtGui.QAction(sbeDownloader)
        self.actionSetSurvey.setEnabled(False)
        self.actionSetSurvey.setObjectName(_fromUtf8("actionSetSurvey"))
        self.menuFile.addAction(self.actionExit)
        self.menuConfigure.addAction(self.actionSetInterval)
        self.menuConfigure.addSeparator()
        self.menuConfigure.addAction(self.actionSetComPort)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuConfigure.menuAction())

        self.retranslateUi(sbeDownloader)
        QtCore.QMetaObject.connectSlotsByName(sbeDownloader)

    def retranslateUi(self, sbeDownloader):
        sbeDownloader.setWindowTitle(_translate("sbeDownloader", "CLAMS SBE39 Downloader", None))
        self.label_15.setText(_translate("sbeDownloader", "Ship", None))
        self.label_16.setText(_translate("sbeDownloader", "Survey", None))
        self.label_17.setText(_translate("sbeDownloader", "Haul", None))
        self.imgLabel.setText(_translate("sbeDownloader", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#0a41a8;\">CLAMS</span></p><p align=\"center\"><span style=\" font-size:16pt; color:#0a41a8;\">SBE39</span></p><p align=\"center\"><span style=\" font-size:16pt; color:#0a41a8;\">Downloader</span></p></body></html>", None))
        self.label_34.setText(_translate("sbeDownloader", "SBE Output", None))
        self.connectButton.setText(_translate("sbeDownloader", "Connect", None))
        self.downloadButton.setText(_translate("sbeDownloader", "Download", None))
        self.startButton.setText(_translate("sbeDownloader", "Start Logging", None))
        self.stopButton.setText(_translate("sbeDownloader", "Stop Logging", None))
        self.statusButton.setText(_translate("sbeDownloader", "Update Status", None))
        self.doneBtn.setText(_translate("sbeDownloader", "Done", None))
        self.menuFile.setTitle(_translate("sbeDownloader", "File", None))
        self.menuConfigure.setTitle(_translate("sbeDownloader", "Configure", None))
        self.actionExit.setText(_translate("sbeDownloader", "Exit", None))
        self.actionSetInterval.setText(_translate("sbeDownloader", "Set SBE Sampling Interval...", None))
        self.actionSetComPort.setText(_translate("sbeDownloader", "Configure COM Port...", None))
        self.actionSetSurvey.setText(_translate("sbeDownloader", "Set Vessel and Survey ID...", None))

