# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\CollectionsDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_collectionsDlg(object):
    def setupUi(self, collectionsDlg):
        collectionsDlg.setObjectName("collectionsDlg")
        collectionsDlg.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(collectionsDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(collectionsDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 0, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(collectionsDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 2, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(collectionsDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 2, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(collectionsDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(collectionsDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(collectionsDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 1, 1, 1, 1)
        self.printExitButton = QtWidgets.QPushButton(collectionsDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.printExitButton.setFont(font)
        self.printExitButton.setObjectName("printExitButton")
        self.gridLayout.addWidget(self.printExitButton, 3, 0, 1, 1)
        self.cancelBtn = QtWidgets.QPushButton(collectionsDlg)
        self.cancelBtn.setMinimumSize(QtCore.QSize(0, 54))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(collectionsDlg)
        QtCore.QMetaObject.connectSlotsByName(collectionsDlg)

    def retranslateUi(self, collectionsDlg):
        _translate = QtCore.QCoreApplication.translate
        collectionsDlg.setWindowTitle(_translate("collectionsDlg", "Collections Dialog"))
        self.checkBox_1.setText(_translate("collectionsDlg", "CheckBox"))
        self.checkBox_6.setText(_translate("collectionsDlg", "CheckBox"))
        self.checkBox_5.setText(_translate("collectionsDlg", "CheckBox"))
        self.checkBox_3.setText(_translate("collectionsDlg", "CheckBox"))
        self.checkBox_2.setText(_translate("collectionsDlg", "CheckBox"))
        self.checkBox_4.setText(_translate("collectionsDlg", "CheckBox"))
        self.printExitButton.setText(_translate("collectionsDlg", "Print Label \n"
"and Exit"))
        self.cancelBtn.setText(_translate("collectionsDlg", "Cancel"))
