# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\ClipDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(264, 237)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pb_clip = QtWidgets.QPushButton(Dialog)
        self.pb_clip.setGeometry(QtCore.QRect(40, 110, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_clip.setFont(font)
        self.pb_clip.setCheckable(False)
        self.pb_clip.setObjectName("pb_clip")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Fin Clips"))
        self.label.setText(_translate("Dialog", "Enter the cell number..."))
        self.pb_clip.setText(_translate("Dialog", "Click here"))
