# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\FEATLuckDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(264, 497)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pb_take_liver = QtWidgets.QPushButton(Dialog)
        self.pb_take_liver.setGeometry(QtCore.QRect(20, 170, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_take_liver.setFont(font)
        self.pb_take_liver.setObjectName("pb_take_liver")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 191, 41))
        self.label_4.setStyleSheet("font: 14pt \"Calibri\";")
        self.label_4.setObjectName("label_4")
        self.l_cur_code = QtWidgets.QLabel(Dialog)
        self.l_cur_code.setGeometry(QtCore.QRect(50, 360, 191, 41))
        self.l_cur_code.setStyleSheet("font: 14pt \"Calibri\";")
        self.l_cur_code.setObjectName("l_cur_code")
        self.cb_nad = QtWidgets.QCheckBox(Dialog)
        self.cb_nad.setGeometry(QtCore.QRect(20, 30, 211, 51))
        self.cb_nad.setStyleSheet("font: 16pt \"Calibri\";")
        self.cb_nad.setObjectName("cb_nad")
        self.cb_liver = QtWidgets.QCheckBox(Dialog)
        self.cb_liver.setGeometry(QtCore.QRect(20, 70, 211, 51))
        self.cb_liver.setStyleSheet("font: 16pt \"Calibri\";")
        self.cb_liver.setObjectName("cb_liver")
        self.pb_cancel = QtWidgets.QPushButton(Dialog)
        self.pb_cancel.setGeometry(QtCore.QRect(30, 420, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setObjectName("pb_cancel")
        self.pb_done = QtWidgets.QPushButton(Dialog)
        self.pb_done.setGeometry(QtCore.QRect(170, 420, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_done.setFont(font)
        self.pb_done.setObjectName("pb_done")
        self.l_samp_num = QtWidgets.QLabel(Dialog)
        self.l_samp_num.setGeometry(QtCore.QRect(10, 110, 241, 41))
        self.l_samp_num.setStyleSheet("font: 14pt \"Calibri\";")
        self.l_samp_num.setObjectName("l_samp_num")
        self.pb_take_gonad = QtWidgets.QPushButton(Dialog)
        self.pb_take_gonad.setGeometry(QtCore.QRect(20, 250, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_take_gonad.setFont(font)
        self.pb_take_gonad.setObjectName("pb_take_gonad")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Luckenbach RNA"))
        self.label.setText(_translate("Dialog", "Luckenbach RNA"))
        self.pb_take_liver.setText(_translate("Dialog", "Take Liver"))
        self.label_4.setText(_translate("Dialog", "Current Barcode"))
        self.l_cur_code.setText(_translate("Dialog", "None"))
        self.cb_nad.setText(_translate("Dialog", "Gonad RNA Taken"))
        self.cb_liver.setText(_translate("Dialog", "Liver RNA Taken"))
        self.pb_cancel.setText(_translate("Dialog", "Cancel"))
        self.pb_done.setText(_translate("Dialog", "Done"))
        self.l_samp_num.setText(_translate("Dialog", "Use Sample Number: "))
        self.pb_take_gonad.setText(_translate("Dialog", "Take Gonad"))
