# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\ListSelDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_listselDialog(object):
    def setupUi(self, listselDialog):
        listselDialog.setObjectName("listselDialog")
        listselDialog.resize(415, 521)
        self.verticalLayout = QtWidgets.QVBoxLayout(listselDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(listselDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.itemList = QtWidgets.QListWidget(listselDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itemList.setFont(font)
        self.itemList.setObjectName("itemList")
        self.verticalLayout.addWidget(self.itemList)
        self.btnFrame = QtWidgets.QFrame(listselDialog)
        self.btnFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.btnFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.btnFrame.setObjectName("btnFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btnFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exitBtn = QtWidgets.QPushButton(self.btnFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout.addWidget(self.exitBtn)
        self.okBtn = QtWidgets.QPushButton(self.btnFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.verticalLayout.addWidget(self.btnFrame)

        self.retranslateUi(listselDialog)
        QtCore.QMetaObject.connectSlotsByName(listselDialog)

    def retranslateUi(self, listselDialog):
        _translate = QtCore.QCoreApplication.translate
        listselDialog.setWindowTitle(_translate("listselDialog", "Select..."))
        self.exitBtn.setText(_translate("listselDialog", "Cancel"))
        self.okBtn.setText(_translate("listselDialog", "OK"))
