# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\MatSelDlgABL.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_matselDlgABL(object):
    def setupUi(self, matselDlgABL):
        matselDlgABL.setObjectName("matselDlgABL")
        matselDlgABL.resize(264, 171)
        self.groupBox = QtWidgets.QGroupBox(matselDlgABL)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 241, 131))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.immatureBtn = QtWidgets.QPushButton(self.groupBox)
        self.immatureBtn.setGeometry(QtCore.QRect(10, 10, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.immatureBtn.setFont(font)
        self.immatureBtn.setObjectName("immatureBtn")
        self.maturingBtn = QtWidgets.QPushButton(self.groupBox)
        self.maturingBtn.setGeometry(QtCore.QRect(10, 70, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maturingBtn.setFont(font)
        self.maturingBtn.setObjectName("maturingBtn")
        self.label = QtWidgets.QLabel(matselDlgABL)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(matselDlgABL)
        QtCore.QMetaObject.connectSlotsByName(matselDlgABL)

    def retranslateUi(self, matselDlgABL):
        _translate = QtCore.QCoreApplication.translate
        matselDlgABL.setWindowTitle(_translate("matselDlgABL", "Maturity Selection"))
        self.immatureBtn.setText(_translate("matselDlgABL", "Immature"))
        self.maturingBtn.setText(_translate("matselDlgABL", "Maturing"))
        self.label.setText(_translate("matselDlgABL", "Select the maturity..."))
