# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\MessageDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_messageDlg(object):
    def setupUi(self, messageDlg):
        messageDlg.setObjectName("messageDlg")
        messageDlg.resize(750, 415)
        self.msgLabel = QtWidgets.QLabel(messageDlg)
        self.msgLabel.setGeometry(QtCore.QRect(300, 20, 431, 301))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.msgLabel.setFont(font)
        self.msgLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.msgLabel.setText("")
        self.msgLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.msgLabel.setWordWrap(True)
        self.msgLabel.setObjectName("msgLabel")
        self.btn_1 = QtWidgets.QPushButton(messageDlg)
        self.btn_1.setGeometry(QtCore.QRect(530, 340, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(messageDlg)
        self.btn_2.setGeometry(QtCore.QRect(10, 340, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.iconLabel = QtWidgets.QLabel(messageDlg)
        self.iconLabel.setGeometry(QtCore.QRect(30, 20, 271, 300))
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.btn_3 = QtWidgets.QPushButton(messageDlg)
        self.btn_3.setGeometry(QtCore.QRect(270, 340, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_3.setFont(font)
        self.btn_3.setText("")
        self.btn_3.setObjectName("btn_3")

        self.retranslateUi(messageDlg)
        QtCore.QMetaObject.connectSlotsByName(messageDlg)

    def retranslateUi(self, messageDlg):
        _translate = QtCore.QCoreApplication.translate
        messageDlg.setWindowTitle(_translate("messageDlg", "Ack.. A Question..."))
        self.btn_1.setText(_translate("messageDlg", "Yes"))
        self.btn_2.setText(_translate("messageDlg", "No"))
