# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\ProcessDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_processDlg(object):
    def setupUi(self, processDlg):
        processDlg.setObjectName("processDlg")
        processDlg.resize(562, 185)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(processDlg.sizePolicy().hasHeightForWidth())
        processDlg.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(processDlg)
        self.label.setGeometry(QtCore.QRect(30, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.haulLabel = QtWidgets.QLabel(processDlg)
        self.haulLabel.setGeometry(QtCore.QRect(280, 20, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.haulLabel.setFont(font)
        self.haulLabel.setText("")
        self.haulLabel.setObjectName("haulLabel")
        self.cancelBtn = QtWidgets.QPushButton(processDlg)
        self.cancelBtn.setGeometry(QtCore.QRect(10, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.editBtn = QtWidgets.QPushButton(processDlg)
        self.editBtn.setGeometry(QtCore.QRect(200, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.procBtn = QtWidgets.QPushButton(processDlg)
        self.procBtn.setGeometry(QtCore.QRect(390, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.procBtn.setFont(font)
        self.procBtn.setObjectName("procBtn")
        self.label_2 = QtWidgets.QLabel(processDlg)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.timeLabel = QtWidgets.QLabel(processDlg)
        self.timeLabel.setGeometry(QtCore.QRect(200, 70, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.timeLabel.setFont(font)
        self.timeLabel.setText("")
        self.timeLabel.setObjectName("timeLabel")

        self.retranslateUi(processDlg)
        QtCore.QMetaObject.connectSlotsByName(processDlg)

    def retranslateUi(self, processDlg):
        _translate = QtCore.QCoreApplication.translate
        processDlg.setWindowTitle(_translate("processDlg", "Process Haul"))
        self.label.setText(_translate("processDlg", "Current Haul is"))
        self.cancelBtn.setText(_translate("processDlg", "Cancel"))
        self.editBtn.setText(_translate("processDlg", "Edit past haul"))
        self.procBtn.setText(_translate("processDlg", "Proceed"))
        self.label_2.setText(_translate("processDlg", "Hauled back at"))
