# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\StreamLoadDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_streamloaddlg(object):
    def setupUi(self, streamloaddlg):
        streamloaddlg.setObjectName("streamloaddlg")
        streamloaddlg.resize(400, 333)
        self.verticalLayout = QtWidgets.QVBoxLayout(streamloaddlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(streamloaddlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.loadSBEBtn = QtWidgets.QPushButton(streamloaddlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.loadSBEBtn.setFont(font)
        self.loadSBEBtn.setObjectName("loadSBEBtn")
        self.verticalLayout.addWidget(self.loadSBEBtn)
        self.depthBtn = QtWidgets.QPushButton(streamloaddlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.depthBtn.setFont(font)
        self.depthBtn.setObjectName("depthBtn")
        self.verticalLayout.addWidget(self.depthBtn)
        self.GPSBtn = QtWidgets.QPushButton(streamloaddlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.GPSBtn.setFont(font)
        self.GPSBtn.setObjectName("GPSBtn")
        self.verticalLayout.addWidget(self.GPSBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(streamloaddlg)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.doneBtn = QtWidgets.QPushButton(streamloaddlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.verticalLayout.addWidget(self.doneBtn)

        self.retranslateUi(streamloaddlg)
        QtCore.QMetaObject.connectSlotsByName(streamloaddlg)

    def retranslateUi(self, streamloaddlg):
        _translate = QtCore.QCoreApplication.translate
        streamloaddlg.setWindowTitle(_translate("streamloaddlg", "CLAMS Utilities"))
        self.label.setText(_translate("streamloaddlg", "Load Stream Data"))
        self.loadSBEBtn.setText(_translate("streamloaddlg", "Load SBE file"))
        self.depthBtn.setText(_translate("streamloaddlg", "Load EK60 Depth Data"))
        self.GPSBtn.setText(_translate("streamloaddlg", "Load MX420 GPS Data"))
        self.doneBtn.setText(_translate("streamloaddlg", "Done"))
