# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\SexSelDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sexselDlg(object):
    def setupUi(self, sexselDlg):
        sexselDlg.setObjectName("sexselDlg")
        sexselDlg.resize(264, 239)
        self.groupBox = QtWidgets.QGroupBox(sexselDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 241, 191))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.maleBtn = QtWidgets.QPushButton(self.groupBox)
        self.maleBtn.setGeometry(QtCore.QRect(10, 10, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maleBtn.setFont(font)
        self.maleBtn.setObjectName("maleBtn")
        self.femaleBtn = QtWidgets.QPushButton(self.groupBox)
        self.femaleBtn.setGeometry(QtCore.QRect(10, 70, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.femaleBtn.setFont(font)
        self.femaleBtn.setObjectName("femaleBtn")
        self.noneBtn = QtWidgets.QPushButton(self.groupBox)
        self.noneBtn.setGeometry(QtCore.QRect(10, 130, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noneBtn.setFont(font)
        self.noneBtn.setObjectName("noneBtn")
        self.label = QtWidgets.QLabel(sexselDlg)
        self.label.setGeometry(QtCore.QRect(10, 10, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(sexselDlg)
        QtCore.QMetaObject.connectSlotsByName(sexselDlg)

    def retranslateUi(self, sexselDlg):
        _translate = QtCore.QCoreApplication.translate
        sexselDlg.setWindowTitle(_translate("sexselDlg", "Sex Selection"))
        self.maleBtn.setText(_translate("sexselDlg", "Male"))
        self.femaleBtn.setText(_translate("sexselDlg", "Female"))
        self.noneBtn.setText(_translate("sexselDlg", "Unsexed"))
        self.label.setText(_translate("sexselDlg", "Select the sex..."))
