# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\sbeSetInterval.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sbeSetInterval(object):
    def setupUi(self, sbeSetInterval):
        sbeSetInterval.setObjectName("sbeSetInterval")
        sbeSetInterval.resize(339, 101)
        sbeSetInterval.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(sbeSetInterval)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(sbeSetInterval)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(sbeSetInterval)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.cbRTO = QtWidgets.QCheckBox(sbeSetInterval)
        self.cbRTO.setText("")
        self.cbRTO.setObjectName("cbRTO")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbRTO)
        self.spinInterval = QtWidgets.QSpinBox(sbeSetInterval)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinInterval.setFont(font)
        self.spinInterval.setMinimum(0)
        self.spinInterval.setMaximum(32766)
        self.spinInterval.setProperty("value", 0)
        self.spinInterval.setObjectName("spinInterval")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinInterval)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbCancel = QtWidgets.QPushButton(sbeSetInterval)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.pbOK = QtWidgets.QPushButton(sbeSetInterval)
        self.pbOK.setObjectName("pbOK")
        self.horizontalLayout.addWidget(self.pbOK)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(sbeSetInterval)
        QtCore.QMetaObject.connectSlotsByName(sbeSetInterval)

    def retranslateUi(self, sbeSetInterval):
        _translate = QtCore.QCoreApplication.translate
        sbeSetInterval.setWindowTitle(_translate("sbeSetInterval", "Set Sampling Interval"))
        self.label.setText(_translate("sbeSetInterval", "SBE Sampling Interval"))
        self.label_2.setText(_translate("sbeSetInterval", "Display Real-Time Output"))
        self.spinInterval.setToolTip(_translate("sbeSetInterval", "Interval (in seconds) between samples."))
        self.spinInterval.setSuffix(_translate("sbeSetInterval", " seconds"))
        self.pbCancel.setText(_translate("sbeSetInterval", "Cancel"))
        self.pbOK.setText(_translate("sbeSetInterval", "OK"))
