# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\sbeSetLocation.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sbeSetLocation(object):
    def setupUi(self, sbeSetLocation):
        sbeSetLocation.setObjectName("sbeSetLocation")
        sbeSetLocation.resize(494, 133)
        sbeSetLocation.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(sbeSetLocation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QLabel(sbeSetLocation)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.cbLocation = QtWidgets.QComboBox(sbeSetLocation)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbLocation.setFont(font)
        self.cbLocation.setObjectName("cbLocation")
        self.verticalLayout.addWidget(self.cbLocation)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbCancel = QtWidgets.QPushButton(sbeSetLocation)
        self.pbCancel.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pbCancel.setFont(font)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.pbOK = QtWidgets.QPushButton(sbeSetLocation)
        self.pbOK.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pbOK.setFont(font)
        self.pbOK.setObjectName("pbOK")
        self.horizontalLayout.addWidget(self.pbOK)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(sbeSetLocation)
        QtCore.QMetaObject.connectSlotsByName(sbeSetLocation)

    def retranslateUi(self, sbeSetLocation):
        _translate = QtCore.QCoreApplication.translate
        sbeSetLocation.setWindowTitle(_translate("sbeSetLocation", "Set SBE Mounting Location"))
        self.text.setText(_translate("sbeSetLocation", "Please specify the SBE Mounting Location "))
        self.pbCancel.setText(_translate("sbeSetLocation", "Cancel"))
        self.pbOK.setText(_translate("sbeSetLocation", "OK"))
