# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\TimeDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_timeDlg(object):
    def setupUi(self, timeDlg):
        timeDlg.setObjectName("timeDlg")
        timeDlg.resize(383, 216)
        self.timeEdit = QtWidgets.QTimeEdit(timeDlg)
        self.timeEdit.setGeometry(QtCore.QRect(20, 100, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeEdit.setFont(font)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(timeDlg)
        self.dateEdit.setGeometry(QtCore.QRect(20, 40, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.okBtn = QtWidgets.QPushButton(timeDlg)
        self.okBtn.setGeometry(QtCore.QRect(220, 160, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.cancelBtn = QtWidgets.QPushButton(timeDlg)
        self.cancelBtn.setGeometry(QtCore.QRect(30, 160, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.label = QtWidgets.QLabel(timeDlg)
        self.label.setGeometry(QtCore.QRect(30, 10, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pbGetCurrentTime = QtWidgets.QPushButton(timeDlg)
        self.pbGetCurrentTime.setGeometry(QtCore.QRect(200, 70, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pbGetCurrentTime.setFont(font)
        self.pbGetCurrentTime.setObjectName("pbGetCurrentTime")

        self.retranslateUi(timeDlg)
        QtCore.QMetaObject.connectSlotsByName(timeDlg)

    def retranslateUi(self, timeDlg):
        _translate = QtCore.QCoreApplication.translate
        timeDlg.setWindowTitle(_translate("timeDlg", "Edit Event Time"))
        self.timeEdit.setDisplayFormat(_translate("timeDlg", "hh:mm:ss"))
        self.okBtn.setText(_translate("timeDlg", "OK"))
        self.cancelBtn.setText(_translate("timeDlg", "Cancel"))
        self.label.setText(_translate("timeDlg", "Enter a date and time"))
        self.pbGetCurrentTime.setText(_translate("timeDlg", "Get Current Time"))
