# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\AFSCGit\CLAMS\application\ui\TypeSelDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_typeselDialog(object):
    def setupUi(self, typeselDialog):
        typeselDialog.setObjectName("typeselDialog")
        typeselDialog.resize(322, 353)
        self.typeBox = QtWidgets.QGroupBox(typeselDialog)
        self.typeBox.setEnabled(True)
        self.typeBox.setGeometry(QtCore.QRect(10, 40, 301, 301))
        self.typeBox.setTitle("")
        self.typeBox.setObjectName("typeBox")
        self.btn_0 = QtWidgets.QPushButton(self.typeBox)
        self.btn_0.setGeometry(QtCore.QRect(10, 10, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_0.setFont(font)
        self.btn_0.setText("")
        self.btn_0.setObjectName("btn_0")
        self.btn_1 = QtWidgets.QPushButton(self.typeBox)
        self.btn_1.setGeometry(QtCore.QRect(10, 80, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_1.setFont(font)
        self.btn_1.setText("")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.typeBox)
        self.btn_2.setGeometry(QtCore.QRect(10, 150, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_2.setFont(font)
        self.btn_2.setText("")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.typeBox)
        self.btn_3.setGeometry(QtCore.QRect(10, 220, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_3.setFont(font)
        self.btn_3.setText("")
        self.btn_3.setObjectName("btn_3")
        self.label = QtWidgets.QLabel(typeselDialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 249, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(typeselDialog)
        QtCore.QMetaObject.connectSlotsByName(typeselDialog)

    def retranslateUi(self, typeselDialog):
        _translate = QtCore.QCoreApplication.translate
        typeselDialog.setWindowTitle(_translate("typeselDialog", "Sample Type"))
        self.label.setText(_translate("typeselDialog", "Basket Sample Type?"))
